/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.04.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Insights for FIRST Power Up qualification and elimination matches.
 */
@ApiModel(description = "Insights for FIRST Power Up qualification and elimination matches.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-23T11:52:56.009-04:00")
public class EventInsights2018 {
    @SerializedName("auto_quest_achieved")
    private List<Float> autoQuestAchieved = new ArrayList<Float>();

    @SerializedName("average_boost_played")
    private Float averageBoostPlayed = null;

    @SerializedName("average_endgame_points")
    private Float averageEndgamePoints = null;

    @SerializedName("average_force_played")
    private Float averageForcePlayed = null;

    @SerializedName("average_foul_score")
    private Float averageFoulScore = null;

    @SerializedName("average_points_auto")
    private Float averagePointsAuto = null;

    @SerializedName("average_points_teleop")
    private Float averagePointsTeleop = null;

    @SerializedName("average_run_points_auto")
    private Float averageRunPointsAuto = null;

    @SerializedName("average_scale_ownership_points")
    private Float averageScaleOwnershipPoints = null;

    @SerializedName("average_scale_ownership_points_auto")
    private Float averageScaleOwnershipPointsAuto = null;

    @SerializedName("average_scale_ownership_points_teleop")
    private Float averageScaleOwnershipPointsTeleop = null;

    @SerializedName("average_score")
    private Float averageScore = null;

    @SerializedName("average_switch_ownership_points")
    private Float averageSwitchOwnershipPoints = null;

    @SerializedName("average_switch_ownership_points_auto")
    private Float averageSwitchOwnershipPointsAuto = null;

    @SerializedName("average_switch_ownership_points_teleop")
    private Float averageSwitchOwnershipPointsTeleop = null;

    @SerializedName("average_vault_points")
    private Float averageVaultPoints = null;

    @SerializedName("average_win_margin")
    private Float averageWinMargin = null;

    @SerializedName("average_win_score")
    private Float averageWinScore = null;

    @SerializedName("boost_played_counts")
    private List<Float> boostPlayedCounts = new ArrayList<Float>();

    @SerializedName("climb_counts")
    private List<Float> climbCounts = new ArrayList<Float>();

    @SerializedName("face_the_boss_achieved")
    private List<Float> faceTheBossAchieved = new ArrayList<Float>();

    @SerializedName("force_played_counts")
    private List<Float> forcePlayedCounts = new ArrayList<Float>();

    @SerializedName("high_score")
    private List<String> highScore = new ArrayList<String>();

    @SerializedName("levitate_played_counts")
    private List<Float> levitatePlayedCounts = new ArrayList<Float>();

    @SerializedName("run_counts_auto")
    private List<Float> runCountsAuto = new ArrayList<Float>();

    @SerializedName("scale_neutral_percentage")
    private Float scaleNeutralPercentage = null;

    @SerializedName("scale_neutral_percentage_auto")
    private Float scaleNeutralPercentageAuto = null;

    @SerializedName("scale_neutral_percentage_teleop")
    private Float scaleNeutralPercentageTeleop = null;

    @SerializedName("switch_owned_counts_auto")
    private List<Float> switchOwnedCountsAuto = new ArrayList<Float>();

    @SerializedName("unicorn_matches")
    private List<Float> unicornMatches = new ArrayList<Float>();

    @SerializedName("winning_opp_switch_denial_percentage_teleop")
    private Float winningOppSwitchDenialPercentageTeleop = null;

    @SerializedName("winning_own_switch_ownership_percentage")
    private Float winningOwnSwitchOwnershipPercentage = null;

    @SerializedName("winning_own_switch_ownership_percentage_auto")
    private Float winningOwnSwitchOwnershipPercentageAuto = null;

    @SerializedName("winning_own_switch_ownership_percentage_teleop")
    private Float winningOwnSwitchOwnershipPercentageTeleop = null;

    @SerializedName("winning_scale_ownership_percentage")
    private Float winningScaleOwnershipPercentage = null;

    @SerializedName("winning_scale_ownership_percentage_auto")
    private Float winningScaleOwnershipPercentageAuto = null;

    @SerializedName("winning_scale_ownership_percentage_teleop")
    private Float winningScaleOwnershipPercentageTeleop = null;

    public EventInsights2018 autoQuestAchieved(List<Float> autoQuestAchieved) {
        this.autoQuestAchieved = autoQuestAchieved;
        return this;
    }

    public EventInsights2018 addAutoQuestAchievedItem(Float autoQuestAchievedItem) {
        this.autoQuestAchieved.add(autoQuestAchievedItem);
        return this;
    }

    /**
     * An array with three values, number of times auto quest was completed, number of opportunities to complete the auto quest, and percentage.
     *
     * @return autoQuestAchieved
     **/
    @ApiModelProperty(required = true, value = "An array with three values, number of times auto quest was completed, number of opportunities to complete the auto quest, and percentage.")
    public List<Float> getAutoQuestAchieved() {
        return autoQuestAchieved;
    }

    public void setAutoQuestAchieved(List<Float> autoQuestAchieved) {
        this.autoQuestAchieved = autoQuestAchieved;
    }

    public EventInsights2018 averageBoostPlayed(Float averageBoostPlayed) {
        this.averageBoostPlayed = averageBoostPlayed;
        return this;
    }

    /**
     * Average number of boost power up scored (out of 3).
     *
     * @return averageBoostPlayed
     **/
    @ApiModelProperty(required = true, value = "Average number of boost power up scored (out of 3).")
    public Float getAverageBoostPlayed() {
        return averageBoostPlayed;
    }

    public void setAverageBoostPlayed(Float averageBoostPlayed) {
        this.averageBoostPlayed = averageBoostPlayed;
    }

    public EventInsights2018 averageEndgamePoints(Float averageEndgamePoints) {
        this.averageEndgamePoints = averageEndgamePoints;
        return this;
    }

    /**
     * Average endgame points.
     *
     * @return averageEndgamePoints
     **/
    @ApiModelProperty(required = true, value = "Average endgame points.")
    public Float getAverageEndgamePoints() {
        return averageEndgamePoints;
    }

    public void setAverageEndgamePoints(Float averageEndgamePoints) {
        this.averageEndgamePoints = averageEndgamePoints;
    }

    public EventInsights2018 averageForcePlayed(Float averageForcePlayed) {
        this.averageForcePlayed = averageForcePlayed;
        return this;
    }

    /**
     * Average number of force power up scored (out of 3).
     *
     * @return averageForcePlayed
     **/
    @ApiModelProperty(required = true, value = "Average number of force power up scored (out of 3).")
    public Float getAverageForcePlayed() {
        return averageForcePlayed;
    }

    public void setAverageForcePlayed(Float averageForcePlayed) {
        this.averageForcePlayed = averageForcePlayed;
    }

    public EventInsights2018 averageFoulScore(Float averageFoulScore) {
        this.averageFoulScore = averageFoulScore;
        return this;
    }

    /**
     * Average foul score.
     *
     * @return averageFoulScore
     **/
    @ApiModelProperty(required = true, value = "Average foul score.")
    public Float getAverageFoulScore() {
        return averageFoulScore;
    }

    public void setAverageFoulScore(Float averageFoulScore) {
        this.averageFoulScore = averageFoulScore;
    }

    public EventInsights2018 averagePointsAuto(Float averagePointsAuto) {
        this.averagePointsAuto = averagePointsAuto;
        return this;
    }

    /**
     * Average points scored during auto.
     *
     * @return averagePointsAuto
     **/
    @ApiModelProperty(required = true, value = "Average points scored during auto.")
    public Float getAveragePointsAuto() {
        return averagePointsAuto;
    }

    public void setAveragePointsAuto(Float averagePointsAuto) {
        this.averagePointsAuto = averagePointsAuto;
    }

    public EventInsights2018 averagePointsTeleop(Float averagePointsTeleop) {
        this.averagePointsTeleop = averagePointsTeleop;
        return this;
    }

    /**
     * Average points scored during teleop.
     *
     * @return averagePointsTeleop
     **/
    @ApiModelProperty(required = true, value = "Average points scored during teleop.")
    public Float getAveragePointsTeleop() {
        return averagePointsTeleop;
    }

    public void setAveragePointsTeleop(Float averagePointsTeleop) {
        this.averagePointsTeleop = averagePointsTeleop;
    }

    public EventInsights2018 averageRunPointsAuto(Float averageRunPointsAuto) {
        this.averageRunPointsAuto = averageRunPointsAuto;
        return this;
    }

    /**
     * Average mobility points scored during auto.
     *
     * @return averageRunPointsAuto
     **/
    @ApiModelProperty(required = true, value = "Average mobility points scored during auto.")
    public Float getAverageRunPointsAuto() {
        return averageRunPointsAuto;
    }

    public void setAverageRunPointsAuto(Float averageRunPointsAuto) {
        this.averageRunPointsAuto = averageRunPointsAuto;
    }

    public EventInsights2018 averageScaleOwnershipPoints(Float averageScaleOwnershipPoints) {
        this.averageScaleOwnershipPoints = averageScaleOwnershipPoints;
        return this;
    }

    /**
     * Average scale ownership points scored.
     *
     * @return averageScaleOwnershipPoints
     **/
    @ApiModelProperty(required = true, value = "Average scale ownership points scored.")
    public Float getAverageScaleOwnershipPoints() {
        return averageScaleOwnershipPoints;
    }

    public void setAverageScaleOwnershipPoints(Float averageScaleOwnershipPoints) {
        this.averageScaleOwnershipPoints = averageScaleOwnershipPoints;
    }

    public EventInsights2018 averageScaleOwnershipPointsAuto(Float averageScaleOwnershipPointsAuto) {
        this.averageScaleOwnershipPointsAuto = averageScaleOwnershipPointsAuto;
        return this;
    }

    /**
     * Average scale ownership points scored during auto.
     *
     * @return averageScaleOwnershipPointsAuto
     **/
    @ApiModelProperty(required = true, value = "Average scale ownership points scored during auto.")
    public Float getAverageScaleOwnershipPointsAuto() {
        return averageScaleOwnershipPointsAuto;
    }

    public void setAverageScaleOwnershipPointsAuto(Float averageScaleOwnershipPointsAuto) {
        this.averageScaleOwnershipPointsAuto = averageScaleOwnershipPointsAuto;
    }

    public EventInsights2018 averageScaleOwnershipPointsTeleop(Float averageScaleOwnershipPointsTeleop) {
        this.averageScaleOwnershipPointsTeleop = averageScaleOwnershipPointsTeleop;
        return this;
    }

    /**
     * Average scale ownership points scored during teleop.
     *
     * @return averageScaleOwnershipPointsTeleop
     **/
    @ApiModelProperty(required = true, value = "Average scale ownership points scored during teleop.")
    public Float getAverageScaleOwnershipPointsTeleop() {
        return averageScaleOwnershipPointsTeleop;
    }

    public void setAverageScaleOwnershipPointsTeleop(Float averageScaleOwnershipPointsTeleop) {
        this.averageScaleOwnershipPointsTeleop = averageScaleOwnershipPointsTeleop;
    }

    public EventInsights2018 averageScore(Float averageScore) {
        this.averageScore = averageScore;
        return this;
    }

    /**
     * Average score.
     *
     * @return averageScore
     **/
    @ApiModelProperty(required = true, value = "Average score.")
    public Float getAverageScore() {
        return averageScore;
    }

    public void setAverageScore(Float averageScore) {
        this.averageScore = averageScore;
    }

    public EventInsights2018 averageSwitchOwnershipPoints(Float averageSwitchOwnershipPoints) {
        this.averageSwitchOwnershipPoints = averageSwitchOwnershipPoints;
        return this;
    }

    /**
     * Average switch ownership points scored.
     *
     * @return averageSwitchOwnershipPoints
     **/
    @ApiModelProperty(required = true, value = "Average switch ownership points scored.")
    public Float getAverageSwitchOwnershipPoints() {
        return averageSwitchOwnershipPoints;
    }

    public void setAverageSwitchOwnershipPoints(Float averageSwitchOwnershipPoints) {
        this.averageSwitchOwnershipPoints = averageSwitchOwnershipPoints;
    }

    public EventInsights2018 averageSwitchOwnershipPointsAuto(Float averageSwitchOwnershipPointsAuto) {
        this.averageSwitchOwnershipPointsAuto = averageSwitchOwnershipPointsAuto;
        return this;
    }

    /**
     * Average switch ownership points scored during auto.
     *
     * @return averageSwitchOwnershipPointsAuto
     **/
    @ApiModelProperty(required = true, value = "Average switch ownership points scored during auto.")
    public Float getAverageSwitchOwnershipPointsAuto() {
        return averageSwitchOwnershipPointsAuto;
    }

    public void setAverageSwitchOwnershipPointsAuto(Float averageSwitchOwnershipPointsAuto) {
        this.averageSwitchOwnershipPointsAuto = averageSwitchOwnershipPointsAuto;
    }

    public EventInsights2018 averageSwitchOwnershipPointsTeleop(Float averageSwitchOwnershipPointsTeleop) {
        this.averageSwitchOwnershipPointsTeleop = averageSwitchOwnershipPointsTeleop;
        return this;
    }

    /**
     * Average switch ownership points scored during teleop.
     *
     * @return averageSwitchOwnershipPointsTeleop
     **/
    @ApiModelProperty(required = true, value = "Average switch ownership points scored during teleop.")
    public Float getAverageSwitchOwnershipPointsTeleop() {
        return averageSwitchOwnershipPointsTeleop;
    }

    public void setAverageSwitchOwnershipPointsTeleop(Float averageSwitchOwnershipPointsTeleop) {
        this.averageSwitchOwnershipPointsTeleop = averageSwitchOwnershipPointsTeleop;
    }

    public EventInsights2018 averageVaultPoints(Float averageVaultPoints) {
        this.averageVaultPoints = averageVaultPoints;
        return this;
    }

    /**
     * Average value points scored.
     *
     * @return averageVaultPoints
     **/
    @ApiModelProperty(required = true, value = "Average value points scored.")
    public Float getAverageVaultPoints() {
        return averageVaultPoints;
    }

    public void setAverageVaultPoints(Float averageVaultPoints) {
        this.averageVaultPoints = averageVaultPoints;
    }

    public EventInsights2018 averageWinMargin(Float averageWinMargin) {
        this.averageWinMargin = averageWinMargin;
        return this;
    }

    /**
     * Average margin of victory.
     *
     * @return averageWinMargin
     **/
    @ApiModelProperty(required = true, value = "Average margin of victory.")
    public Float getAverageWinMargin() {
        return averageWinMargin;
    }

    public void setAverageWinMargin(Float averageWinMargin) {
        this.averageWinMargin = averageWinMargin;
    }

    public EventInsights2018 averageWinScore(Float averageWinScore) {
        this.averageWinScore = averageWinScore;
        return this;
    }

    /**
     * Average winning score.
     *
     * @return averageWinScore
     **/
    @ApiModelProperty(required = true, value = "Average winning score.")
    public Float getAverageWinScore() {
        return averageWinScore;
    }

    public void setAverageWinScore(Float averageWinScore) {
        this.averageWinScore = averageWinScore;
    }

    public EventInsights2018 boostPlayedCounts(List<Float> boostPlayedCounts) {
        this.boostPlayedCounts = boostPlayedCounts;
        return this;
    }

    public EventInsights2018 addBoostPlayedCountsItem(Float boostPlayedCountsItem) {
        this.boostPlayedCounts.add(boostPlayedCountsItem);
        return this;
    }

    /**
     * An array with three values, number of times a boost power up was played, number of opportunities to play a boost power up, and percentage.
     *
     * @return boostPlayedCounts
     **/
    @ApiModelProperty(required = true, value = "An array with three values, number of times a boost power up was played, number of opportunities to play a boost power up, and percentage.")
    public List<Float> getBoostPlayedCounts() {
        return boostPlayedCounts;
    }

    public void setBoostPlayedCounts(List<Float> boostPlayedCounts) {
        this.boostPlayedCounts = boostPlayedCounts;
    }

    public EventInsights2018 climbCounts(List<Float> climbCounts) {
        this.climbCounts = climbCounts;
        return this;
    }

    public EventInsights2018 addClimbCountsItem(Float climbCountsItem) {
        this.climbCounts.add(climbCountsItem);
        return this;
    }

    /**
     * An array with three values, number of times a climb occurred, number of opportunities to climb, and percentage.
     *
     * @return climbCounts
     **/
    @ApiModelProperty(required = true, value = "An array with three values, number of times a climb occurred, number of opportunities to climb, and percentage.")
    public List<Float> getClimbCounts() {
        return climbCounts;
    }

    public void setClimbCounts(List<Float> climbCounts) {
        this.climbCounts = climbCounts;
    }

    public EventInsights2018 faceTheBossAchieved(List<Float> faceTheBossAchieved) {
        this.faceTheBossAchieved = faceTheBossAchieved;
        return this;
    }

    public EventInsights2018 addFaceTheBossAchievedItem(Float faceTheBossAchievedItem) {
        this.faceTheBossAchieved.add(faceTheBossAchievedItem);
        return this;
    }

    /**
     * An array with three values, number of times an alliance faced the boss, number of opportunities to face the boss, and percentage.
     *
     * @return faceTheBossAchieved
     **/
    @ApiModelProperty(required = true, value = "An array with three values, number of times an alliance faced the boss, number of opportunities to face the boss, and percentage.")
    public List<Float> getFaceTheBossAchieved() {
        return faceTheBossAchieved;
    }

    public void setFaceTheBossAchieved(List<Float> faceTheBossAchieved) {
        this.faceTheBossAchieved = faceTheBossAchieved;
    }

    public EventInsights2018 forcePlayedCounts(List<Float> forcePlayedCounts) {
        this.forcePlayedCounts = forcePlayedCounts;
        return this;
    }

    public EventInsights2018 addForcePlayedCountsItem(Float forcePlayedCountsItem) {
        this.forcePlayedCounts.add(forcePlayedCountsItem);
        return this;
    }

    /**
     * An array with three values, number of times a force power up was played, number of opportunities to play a force power up, and percentage.
     *
     * @return forcePlayedCounts
     **/
    @ApiModelProperty(required = true, value = "An array with three values, number of times a force power up was played, number of opportunities to play a force power up, and percentage.")
    public List<Float> getForcePlayedCounts() {
        return forcePlayedCounts;
    }

    public void setForcePlayedCounts(List<Float> forcePlayedCounts) {
        this.forcePlayedCounts = forcePlayedCounts;
    }

    public EventInsights2018 highScore(List<String> highScore) {
        this.highScore = highScore;
        return this;
    }

    public EventInsights2018 addHighScoreItem(String highScoreItem) {
        this.highScore.add(highScoreItem);
        return this;
    }

    /**
     * An array with three values, high score, match key from the match with the high score, and the name of the match
     *
     * @return highScore
     **/
    @ApiModelProperty(required = true, value = "An array with three values, high score, match key from the match with the high score, and the name of the match")
    public List<String> getHighScore() {
        return highScore;
    }

    public void setHighScore(List<String> highScore) {
        this.highScore = highScore;
    }

    public EventInsights2018 levitatePlayedCounts(List<Float> levitatePlayedCounts) {
        this.levitatePlayedCounts = levitatePlayedCounts;
        return this;
    }

    public EventInsights2018 addLevitatePlayedCountsItem(Float levitatePlayedCountsItem) {
        this.levitatePlayedCounts.add(levitatePlayedCountsItem);
        return this;
    }

    /**
     * An array with three values, number of times a levitate power up was played, number of opportunities to play a levitate power up, and percentage.
     *
     * @return levitatePlayedCounts
     **/
    @ApiModelProperty(required = true, value = "An array with three values, number of times a levitate power up was played, number of opportunities to play a levitate power up, and percentage.")
    public List<Float> getLevitatePlayedCounts() {
        return levitatePlayedCounts;
    }

    public void setLevitatePlayedCounts(List<Float> levitatePlayedCounts) {
        this.levitatePlayedCounts = levitatePlayedCounts;
    }

    public EventInsights2018 runCountsAuto(List<Float> runCountsAuto) {
        this.runCountsAuto = runCountsAuto;
        return this;
    }

    public EventInsights2018 addRunCountsAutoItem(Float runCountsAutoItem) {
        this.runCountsAuto.add(runCountsAutoItem);
        return this;
    }

    /**
     * An array with three values, number of times a team scored mobility points in auto, number of opportunities to score mobility points in auto, and percentage.
     *
     * @return runCountsAuto
     **/
    @ApiModelProperty(required = true, value = "An array with three values, number of times a team scored mobility points in auto, number of opportunities to score mobility points in auto, and percentage.")
    public List<Float> getRunCountsAuto() {
        return runCountsAuto;
    }

    public void setRunCountsAuto(List<Float> runCountsAuto) {
        this.runCountsAuto = runCountsAuto;
    }

    public EventInsights2018 scaleNeutralPercentage(Float scaleNeutralPercentage) {
        this.scaleNeutralPercentage = scaleNeutralPercentage;
        return this;
    }

    /**
     * Average scale neutral percentage.
     *
     * @return scaleNeutralPercentage
     **/
    @ApiModelProperty(required = true, value = "Average scale neutral percentage.")
    public Float getScaleNeutralPercentage() {
        return scaleNeutralPercentage;
    }

    public void setScaleNeutralPercentage(Float scaleNeutralPercentage) {
        this.scaleNeutralPercentage = scaleNeutralPercentage;
    }

    public EventInsights2018 scaleNeutralPercentageAuto(Float scaleNeutralPercentageAuto) {
        this.scaleNeutralPercentageAuto = scaleNeutralPercentageAuto;
        return this;
    }

    /**
     * Average scale neutral percentage during auto.
     *
     * @return scaleNeutralPercentageAuto
     **/
    @ApiModelProperty(required = true, value = "Average scale neutral percentage during auto.")
    public Float getScaleNeutralPercentageAuto() {
        return scaleNeutralPercentageAuto;
    }

    public void setScaleNeutralPercentageAuto(Float scaleNeutralPercentageAuto) {
        this.scaleNeutralPercentageAuto = scaleNeutralPercentageAuto;
    }

    public EventInsights2018 scaleNeutralPercentageTeleop(Float scaleNeutralPercentageTeleop) {
        this.scaleNeutralPercentageTeleop = scaleNeutralPercentageTeleop;
        return this;
    }

    /**
     * Average scale neutral percentage during teleop.
     *
     * @return scaleNeutralPercentageTeleop
     **/
    @ApiModelProperty(required = true, value = "Average scale neutral percentage during teleop.")
    public Float getScaleNeutralPercentageTeleop() {
        return scaleNeutralPercentageTeleop;
    }

    public void setScaleNeutralPercentageTeleop(Float scaleNeutralPercentageTeleop) {
        this.scaleNeutralPercentageTeleop = scaleNeutralPercentageTeleop;
    }

    public EventInsights2018 switchOwnedCountsAuto(List<Float> switchOwnedCountsAuto) {
        this.switchOwnedCountsAuto = switchOwnedCountsAuto;
        return this;
    }

    public EventInsights2018 addSwitchOwnedCountsAutoItem(Float switchOwnedCountsAutoItem) {
        this.switchOwnedCountsAuto.add(switchOwnedCountsAutoItem);
        return this;
    }

    /**
     * An array with three values, number of times a switch was owned during auto, number of opportunities to own a switch during auto, and percentage.
     *
     * @return switchOwnedCountsAuto
     **/
    @ApiModelProperty(required = true, value = "An array with three values, number of times a switch was owned during auto, number of opportunities to own a switch during auto, and percentage.")
    public List<Float> getSwitchOwnedCountsAuto() {
        return switchOwnedCountsAuto;
    }

    public void setSwitchOwnedCountsAuto(List<Float> switchOwnedCountsAuto) {
        this.switchOwnedCountsAuto = switchOwnedCountsAuto;
    }

    public EventInsights2018 unicornMatches(List<Float> unicornMatches) {
        this.unicornMatches = unicornMatches;
        return this;
    }

    public EventInsights2018 addUnicornMatchesItem(Float unicornMatchesItem) {
        this.unicornMatches.add(unicornMatchesItem);
        return this;
    }

    /**
     * An array with three values, number of times a unicorn match (Win + Auto Quest + Face the Boss) occurred, number of opportunities to have a unicorn match, and percentage.
     *
     * @return unicornMatches
     **/
    @ApiModelProperty(required = true, value = "An array with three values, number of times a unicorn match (Win + Auto Quest + Face the Boss) occurred, number of opportunities to have a unicorn match, and percentage.")
    public List<Float> getUnicornMatches() {
        return unicornMatches;
    }

    public void setUnicornMatches(List<Float> unicornMatches) {
        this.unicornMatches = unicornMatches;
    }

    public EventInsights2018 winningOppSwitchDenialPercentageTeleop(Float winningOppSwitchDenialPercentageTeleop) {
        this.winningOppSwitchDenialPercentageTeleop = winningOppSwitchDenialPercentageTeleop;
        return this;
    }

    /**
     * Average opposing switch denail percentage for the winning alliance during teleop.
     *
     * @return winningOppSwitchDenialPercentageTeleop
     **/
    @ApiModelProperty(required = true, value = "Average opposing switch denail percentage for the winning alliance during teleop.")
    public Float getWinningOppSwitchDenialPercentageTeleop() {
        return winningOppSwitchDenialPercentageTeleop;
    }

    public void setWinningOppSwitchDenialPercentageTeleop(Float winningOppSwitchDenialPercentageTeleop) {
        this.winningOppSwitchDenialPercentageTeleop = winningOppSwitchDenialPercentageTeleop;
    }

    public EventInsights2018 winningOwnSwitchOwnershipPercentage(Float winningOwnSwitchOwnershipPercentage) {
        this.winningOwnSwitchOwnershipPercentage = winningOwnSwitchOwnershipPercentage;
        return this;
    }

    /**
     * Average own switch ownership percentage for the winning alliance.
     *
     * @return winningOwnSwitchOwnershipPercentage
     **/
    @ApiModelProperty(required = true, value = "Average own switch ownership percentage for the winning alliance.")
    public Float getWinningOwnSwitchOwnershipPercentage() {
        return winningOwnSwitchOwnershipPercentage;
    }

    public void setWinningOwnSwitchOwnershipPercentage(Float winningOwnSwitchOwnershipPercentage) {
        this.winningOwnSwitchOwnershipPercentage = winningOwnSwitchOwnershipPercentage;
    }

    public EventInsights2018 winningOwnSwitchOwnershipPercentageAuto(Float winningOwnSwitchOwnershipPercentageAuto) {
        this.winningOwnSwitchOwnershipPercentageAuto = winningOwnSwitchOwnershipPercentageAuto;
        return this;
    }

    /**
     * Average own switch ownership percentage for the winning alliance during auto.
     *
     * @return winningOwnSwitchOwnershipPercentageAuto
     **/
    @ApiModelProperty(required = true, value = "Average own switch ownership percentage for the winning alliance during auto.")
    public Float getWinningOwnSwitchOwnershipPercentageAuto() {
        return winningOwnSwitchOwnershipPercentageAuto;
    }

    public void setWinningOwnSwitchOwnershipPercentageAuto(Float winningOwnSwitchOwnershipPercentageAuto) {
        this.winningOwnSwitchOwnershipPercentageAuto = winningOwnSwitchOwnershipPercentageAuto;
    }

    public EventInsights2018 winningOwnSwitchOwnershipPercentageTeleop(Float winningOwnSwitchOwnershipPercentageTeleop) {
        this.winningOwnSwitchOwnershipPercentageTeleop = winningOwnSwitchOwnershipPercentageTeleop;
        return this;
    }

    /**
     * Average own switch ownership percentage for the winning alliance during teleop.
     *
     * @return winningOwnSwitchOwnershipPercentageTeleop
     **/
    @ApiModelProperty(required = true, value = "Average own switch ownership percentage for the winning alliance during teleop.")
    public Float getWinningOwnSwitchOwnershipPercentageTeleop() {
        return winningOwnSwitchOwnershipPercentageTeleop;
    }

    public void setWinningOwnSwitchOwnershipPercentageTeleop(Float winningOwnSwitchOwnershipPercentageTeleop) {
        this.winningOwnSwitchOwnershipPercentageTeleop = winningOwnSwitchOwnershipPercentageTeleop;
    }

    public EventInsights2018 winningScaleOwnershipPercentage(Float winningScaleOwnershipPercentage) {
        this.winningScaleOwnershipPercentage = winningScaleOwnershipPercentage;
        return this;
    }

    /**
     * Average scale ownership percentage for the winning alliance.
     *
     * @return winningScaleOwnershipPercentage
     **/
    @ApiModelProperty(required = true, value = "Average scale ownership percentage for the winning alliance.")
    public Float getWinningScaleOwnershipPercentage() {
        return winningScaleOwnershipPercentage;
    }

    public void setWinningScaleOwnershipPercentage(Float winningScaleOwnershipPercentage) {
        this.winningScaleOwnershipPercentage = winningScaleOwnershipPercentage;
    }

    public EventInsights2018 winningScaleOwnershipPercentageAuto(Float winningScaleOwnershipPercentageAuto) {
        this.winningScaleOwnershipPercentageAuto = winningScaleOwnershipPercentageAuto;
        return this;
    }

    /**
     * Average scale ownership percentage for the winning alliance during auto.
     *
     * @return winningScaleOwnershipPercentageAuto
     **/
    @ApiModelProperty(required = true, value = "Average scale ownership percentage for the winning alliance during auto.")
    public Float getWinningScaleOwnershipPercentageAuto() {
        return winningScaleOwnershipPercentageAuto;
    }

    public void setWinningScaleOwnershipPercentageAuto(Float winningScaleOwnershipPercentageAuto) {
        this.winningScaleOwnershipPercentageAuto = winningScaleOwnershipPercentageAuto;
    }

    public EventInsights2018 winningScaleOwnershipPercentageTeleop(Float winningScaleOwnershipPercentageTeleop) {
        this.winningScaleOwnershipPercentageTeleop = winningScaleOwnershipPercentageTeleop;
        return this;
    }

    /**
     * Average scale ownership percentage for the winning alliance during teleop.
     *
     * @return winningScaleOwnershipPercentageTeleop
     **/
    @ApiModelProperty(required = true, value = "Average scale ownership percentage for the winning alliance during teleop.")
    public Float getWinningScaleOwnershipPercentageTeleop() {
        return winningScaleOwnershipPercentageTeleop;
    }

    public void setWinningScaleOwnershipPercentageTeleop(Float winningScaleOwnershipPercentageTeleop) {
        this.winningScaleOwnershipPercentageTeleop = winningScaleOwnershipPercentageTeleop;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EventInsights2018 eventInsights2018 = (EventInsights2018) o;
        return Objects.equals(this.autoQuestAchieved, eventInsights2018.autoQuestAchieved) &&
                Objects.equals(this.averageBoostPlayed, eventInsights2018.averageBoostPlayed) &&
                Objects.equals(this.averageEndgamePoints, eventInsights2018.averageEndgamePoints) &&
                Objects.equals(this.averageForcePlayed, eventInsights2018.averageForcePlayed) &&
                Objects.equals(this.averageFoulScore, eventInsights2018.averageFoulScore) &&
                Objects.equals(this.averagePointsAuto, eventInsights2018.averagePointsAuto) &&
                Objects.equals(this.averagePointsTeleop, eventInsights2018.averagePointsTeleop) &&
                Objects.equals(this.averageRunPointsAuto, eventInsights2018.averageRunPointsAuto) &&
                Objects.equals(this.averageScaleOwnershipPoints, eventInsights2018.averageScaleOwnershipPoints) &&
                Objects.equals(this.averageScaleOwnershipPointsAuto, eventInsights2018.averageScaleOwnershipPointsAuto) &&
                Objects.equals(this.averageScaleOwnershipPointsTeleop, eventInsights2018.averageScaleOwnershipPointsTeleop) &&
                Objects.equals(this.averageScore, eventInsights2018.averageScore) &&
                Objects.equals(this.averageSwitchOwnershipPoints, eventInsights2018.averageSwitchOwnershipPoints) &&
                Objects.equals(this.averageSwitchOwnershipPointsAuto, eventInsights2018.averageSwitchOwnershipPointsAuto) &&
                Objects.equals(this.averageSwitchOwnershipPointsTeleop, eventInsights2018.averageSwitchOwnershipPointsTeleop) &&
                Objects.equals(this.averageVaultPoints, eventInsights2018.averageVaultPoints) &&
                Objects.equals(this.averageWinMargin, eventInsights2018.averageWinMargin) &&
                Objects.equals(this.averageWinScore, eventInsights2018.averageWinScore) &&
                Objects.equals(this.boostPlayedCounts, eventInsights2018.boostPlayedCounts) &&
                Objects.equals(this.climbCounts, eventInsights2018.climbCounts) &&
                Objects.equals(this.faceTheBossAchieved, eventInsights2018.faceTheBossAchieved) &&
                Objects.equals(this.forcePlayedCounts, eventInsights2018.forcePlayedCounts) &&
                Objects.equals(this.highScore, eventInsights2018.highScore) &&
                Objects.equals(this.levitatePlayedCounts, eventInsights2018.levitatePlayedCounts) &&
                Objects.equals(this.runCountsAuto, eventInsights2018.runCountsAuto) &&
                Objects.equals(this.scaleNeutralPercentage, eventInsights2018.scaleNeutralPercentage) &&
                Objects.equals(this.scaleNeutralPercentageAuto, eventInsights2018.scaleNeutralPercentageAuto) &&
                Objects.equals(this.scaleNeutralPercentageTeleop, eventInsights2018.scaleNeutralPercentageTeleop) &&
                Objects.equals(this.switchOwnedCountsAuto, eventInsights2018.switchOwnedCountsAuto) &&
                Objects.equals(this.unicornMatches, eventInsights2018.unicornMatches) &&
                Objects.equals(this.winningOppSwitchDenialPercentageTeleop, eventInsights2018.winningOppSwitchDenialPercentageTeleop) &&
                Objects.equals(this.winningOwnSwitchOwnershipPercentage, eventInsights2018.winningOwnSwitchOwnershipPercentage) &&
                Objects.equals(this.winningOwnSwitchOwnershipPercentageAuto, eventInsights2018.winningOwnSwitchOwnershipPercentageAuto) &&
                Objects.equals(this.winningOwnSwitchOwnershipPercentageTeleop, eventInsights2018.winningOwnSwitchOwnershipPercentageTeleop) &&
                Objects.equals(this.winningScaleOwnershipPercentage, eventInsights2018.winningScaleOwnershipPercentage) &&
                Objects.equals(this.winningScaleOwnershipPercentageAuto, eventInsights2018.winningScaleOwnershipPercentageAuto) &&
                Objects.equals(this.winningScaleOwnershipPercentageTeleop, eventInsights2018.winningScaleOwnershipPercentageTeleop);
    }

    @Override
    public int hashCode() {
        return Objects.hash(autoQuestAchieved, averageBoostPlayed, averageEndgamePoints, averageForcePlayed, averageFoulScore, averagePointsAuto, averagePointsTeleop, averageRunPointsAuto, averageScaleOwnershipPoints, averageScaleOwnershipPointsAuto, averageScaleOwnershipPointsTeleop, averageScore, averageSwitchOwnershipPoints, averageSwitchOwnershipPointsAuto, averageSwitchOwnershipPointsTeleop, averageVaultPoints, averageWinMargin, averageWinScore, boostPlayedCounts, climbCounts, faceTheBossAchieved, forcePlayedCounts, highScore, levitatePlayedCounts, runCountsAuto, scaleNeutralPercentage, scaleNeutralPercentageAuto, scaleNeutralPercentageTeleop, switchOwnedCountsAuto, unicornMatches, winningOppSwitchDenialPercentageTeleop, winningOwnSwitchOwnershipPercentage, winningOwnSwitchOwnershipPercentageAuto, winningOwnSwitchOwnershipPercentageTeleop, winningScaleOwnershipPercentage, winningScaleOwnershipPercentageAuto, winningScaleOwnershipPercentageTeleop);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EventInsights2018 {\n");

        sb.append("    autoQuestAchieved: ").append(toIndentedString(autoQuestAchieved)).append("\n");
        sb.append("    averageBoostPlayed: ").append(toIndentedString(averageBoostPlayed)).append("\n");
        sb.append("    averageEndgamePoints: ").append(toIndentedString(averageEndgamePoints)).append("\n");
        sb.append("    averageForcePlayed: ").append(toIndentedString(averageForcePlayed)).append("\n");
        sb.append("    averageFoulScore: ").append(toIndentedString(averageFoulScore)).append("\n");
        sb.append("    averagePointsAuto: ").append(toIndentedString(averagePointsAuto)).append("\n");
        sb.append("    averagePointsTeleop: ").append(toIndentedString(averagePointsTeleop)).append("\n");
        sb.append("    averageRunPointsAuto: ").append(toIndentedString(averageRunPointsAuto)).append("\n");
        sb.append("    averageScaleOwnershipPoints: ").append(toIndentedString(averageScaleOwnershipPoints)).append("\n");
        sb.append("    averageScaleOwnershipPointsAuto: ").append(toIndentedString(averageScaleOwnershipPointsAuto)).append("\n");
        sb.append("    averageScaleOwnershipPointsTeleop: ").append(toIndentedString(averageScaleOwnershipPointsTeleop)).append("\n");
        sb.append("    averageScore: ").append(toIndentedString(averageScore)).append("\n");
        sb.append("    averageSwitchOwnershipPoints: ").append(toIndentedString(averageSwitchOwnershipPoints)).append("\n");
        sb.append("    averageSwitchOwnershipPointsAuto: ").append(toIndentedString(averageSwitchOwnershipPointsAuto)).append("\n");
        sb.append("    averageSwitchOwnershipPointsTeleop: ").append(toIndentedString(averageSwitchOwnershipPointsTeleop)).append("\n");
        sb.append("    averageVaultPoints: ").append(toIndentedString(averageVaultPoints)).append("\n");
        sb.append("    averageWinMargin: ").append(toIndentedString(averageWinMargin)).append("\n");
        sb.append("    averageWinScore: ").append(toIndentedString(averageWinScore)).append("\n");
        sb.append("    boostPlayedCounts: ").append(toIndentedString(boostPlayedCounts)).append("\n");
        sb.append("    climbCounts: ").append(toIndentedString(climbCounts)).append("\n");
        sb.append("    faceTheBossAchieved: ").append(toIndentedString(faceTheBossAchieved)).append("\n");
        sb.append("    forcePlayedCounts: ").append(toIndentedString(forcePlayedCounts)).append("\n");
        sb.append("    highScore: ").append(toIndentedString(highScore)).append("\n");
        sb.append("    levitatePlayedCounts: ").append(toIndentedString(levitatePlayedCounts)).append("\n");
        sb.append("    runCountsAuto: ").append(toIndentedString(runCountsAuto)).append("\n");
        sb.append("    scaleNeutralPercentage: ").append(toIndentedString(scaleNeutralPercentage)).append("\n");
        sb.append("    scaleNeutralPercentageAuto: ").append(toIndentedString(scaleNeutralPercentageAuto)).append("\n");
        sb.append("    scaleNeutralPercentageTeleop: ").append(toIndentedString(scaleNeutralPercentageTeleop)).append("\n");
        sb.append("    switchOwnedCountsAuto: ").append(toIndentedString(switchOwnedCountsAuto)).append("\n");
        sb.append("    unicornMatches: ").append(toIndentedString(unicornMatches)).append("\n");
        sb.append("    winningOppSwitchDenialPercentageTeleop: ").append(toIndentedString(winningOppSwitchDenialPercentageTeleop)).append("\n");
        sb.append("    winningOwnSwitchOwnershipPercentage: ").append(toIndentedString(winningOwnSwitchOwnershipPercentage)).append("\n");
        sb.append("    winningOwnSwitchOwnershipPercentageAuto: ").append(toIndentedString(winningOwnSwitchOwnershipPercentageAuto)).append("\n");
        sb.append("    winningOwnSwitchOwnershipPercentageTeleop: ").append(toIndentedString(winningOwnSwitchOwnershipPercentageTeleop)).append("\n");
        sb.append("    winningScaleOwnershipPercentage: ").append(toIndentedString(winningScaleOwnershipPercentage)).append("\n");
        sb.append("    winningScaleOwnershipPercentageAuto: ").append(toIndentedString(winningScaleOwnershipPercentageAuto)).append("\n");
        sb.append("    winningScaleOwnershipPercentageTeleop: ").append(toIndentedString(winningScaleOwnershipPercentageTeleop)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

