/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * EventRankingSortOrderInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-01T17:18:29.994708-05:00[US/Eastern]")
public class EventRankingSortOrderInfo {
  @SerializedName("precision")
  private Integer precision = null;

  @SerializedName("name")
  private String name = null;

  public EventRankingSortOrderInfo precision(Integer precision) {
    this.precision = precision;
    return this;
  }

   /**
   * Integer expressing the number of digits of precision in the number provided in &#x60;sort_orders&#x60;.
   * @return precision
  **/
  @Schema(required = true, description = "Integer expressing the number of digits of precision in the number provided in `sort_orders`.")
  public Integer getPrecision() {
    return precision;
  }

  public void setPrecision(Integer precision) {
    this.precision = precision;
  }

  public EventRankingSortOrderInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the field used in the &#x60;sort_order&#x60; array.
   * @return name
  **/
  @Schema(required = true, description = "Name of the field used in the `sort_order` array.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventRankingSortOrderInfo eventRankingSortOrderInfo = (EventRankingSortOrderInfo) o;
    return Objects.equals(this.precision, eventRankingSortOrderInfo.precision) &&
        Objects.equals(this.name, eventRankingSortOrderInfo.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(precision, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventRankingSortOrderInfo {\n");
    
    sb.append("    precision: ").append(toIndentedString(precision)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
