/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.04.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * MatchVideos
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-05T12:05:14.488-05:00")
public class MatchVideos {
    @SerializedName("key")
    private String key = null;

    @SerializedName("type")
    private String type = null;

    public MatchVideos key(String key) {
        this.key = key;
        return this;
    }

    /**
     * Unique key representing this video
     *
     * @return key
     **/
    @ApiModelProperty(value = "Unique key representing this video")
    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public MatchVideos type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Can be one of &#39;youtube&#39; or &#39;tba&#39;
     *
     * @return type
     **/
    @ApiModelProperty(value = "Can be one of 'youtube' or 'tba'")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MatchVideos matchVideos = (MatchVideos) o;
        return Objects.equals(this.key, matchVideos.key) &&
                Objects.equals(this.type, matchVideos.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(key, type);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MatchVideos {\n");

        sb.append("    key: ").append(toIndentedString(key)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

