/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.04.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * MatchScoreBreakdown2019Alliance
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-05T12:05:14.488-05:00")
public class MatchScoreBreakdown2019Alliance {
    @SerializedName("adjustPoints")
    private Integer adjustPoints = null;

    @SerializedName("autoPoints")
    private Integer autoPoints = null;

    @SerializedName("bay1")
    private String bay1 = null;

    @SerializedName("bay2")
    private String bay2 = null;

    @SerializedName("bay3")
    private String bay3 = null;

    @SerializedName("bay4")
    private String bay4 = null;

    @SerializedName("bay5")
    private String bay5 = null;

    @SerializedName("bay6")
    private String bay6 = null;

    @SerializedName("bay7")
    private String bay7 = null;

    @SerializedName("bay8")
    private String bay8 = null;

    @SerializedName("cargoPoints")
    private Integer cargoPoints = null;

    @SerializedName("completeRocketRankingPoint")
    private Boolean completeRocketRankingPoint = null;

    @SerializedName("completedRocketFar")
    private Boolean completedRocketFar = null;

    @SerializedName("completedRocketNear")
    private Boolean completedRocketNear = null;

    @SerializedName("endgameRobot1")
    private String endgameRobot1 = null;

    @SerializedName("endgameRobot2")
    private String endgameRobot2 = null;

    @SerializedName("endgameRobot3")
    private String endgameRobot3 = null;

    @SerializedName("foulCount")
    private Integer foulCount = null;

    @SerializedName("foulPoints")
    private Integer foulPoints = null;

    @SerializedName("habClimbPoints")
    private Integer habClimbPoints = null;

    @SerializedName("habDockingRankingPoint")
    private Boolean habDockingRankingPoint = null;

    @SerializedName("habLineRobot1")
    private String habLineRobot1 = null;

    @SerializedName("habLineRobot2")
    private String habLineRobot2 = null;

    @SerializedName("habLineRobot3")
    private String habLineRobot3 = null;

    @SerializedName("hatchPanelPoints")
    private Integer hatchPanelPoints = null;

    @SerializedName("lowLeftRocketFar")
    private String lowLeftRocketFar = null;

    @SerializedName("lowLeftRocketNear")
    private String lowLeftRocketNear = null;

    @SerializedName("lowRightRocketFar")
    private String lowRightRocketFar = null;

    @SerializedName("lowRightRocketNear")
    private String lowRightRocketNear = null;

    @SerializedName("midLeftRocketFar")
    private String midLeftRocketFar = null;

    @SerializedName("midLeftRocketNear")
    private String midLeftRocketNear = null;

    @SerializedName("midRightRocketFar")
    private String midRightRocketFar = null;

    @SerializedName("midRightRocketNear")
    private String midRightRocketNear = null;

    @SerializedName("preMatchBay1")
    private String preMatchBay1 = null;

    @SerializedName("preMatchBay2")
    private String preMatchBay2 = null;

    @SerializedName("preMatchBay3")
    private String preMatchBay3 = null;

    @SerializedName("preMatchBay6")
    private String preMatchBay6 = null;

    @SerializedName("preMatchBay7")
    private String preMatchBay7 = null;

    @SerializedName("preMatchBay8")
    private String preMatchBay8 = null;

    @SerializedName("preMatchLevelRobot1")
    private String preMatchLevelRobot1 = null;

    @SerializedName("preMatchLevelRobot2")
    private String preMatchLevelRobot2 = null;

    @SerializedName("preMatchLevelRobot3")
    private String preMatchLevelRobot3 = null;

    @SerializedName("rp")
    private Integer rp = null;

    @SerializedName("sandStormBonusPoints")
    private Integer sandStormBonusPoints = null;

    @SerializedName("techFoulCount")
    private Integer techFoulCount = null;

    @SerializedName("teleopPoints")
    private Integer teleopPoints = null;

    @SerializedName("topLeftRocketFar")
    private String topLeftRocketFar = null;

    @SerializedName("topLeftRocketNear")
    private String topLeftRocketNear = null;

    @SerializedName("topRightRocketFar")
    private String topRightRocketFar = null;

    @SerializedName("topRightRocketNear")
    private String topRightRocketNear = null;

    @SerializedName("totalPoints")
    private Integer totalPoints = null;

    public MatchScoreBreakdown2019Alliance adjustPoints(Integer adjustPoints) {
        this.adjustPoints = adjustPoints;
        return this;
    }

    /**
     * Get adjustPoints
     *
     * @return adjustPoints
     **/
    @ApiModelProperty(value = "")
    public Integer getAdjustPoints() {
        return adjustPoints;
    }

    public void setAdjustPoints(Integer adjustPoints) {
        this.adjustPoints = adjustPoints;
    }

    public MatchScoreBreakdown2019Alliance autoPoints(Integer autoPoints) {
        this.autoPoints = autoPoints;
        return this;
    }

    /**
     * Get autoPoints
     *
     * @return autoPoints
     **/
    @ApiModelProperty(value = "")
    public Integer getAutoPoints() {
        return autoPoints;
    }

    public void setAutoPoints(Integer autoPoints) {
        this.autoPoints = autoPoints;
    }

    public MatchScoreBreakdown2019Alliance bay1(String bay1) {
        this.bay1 = bay1;
        return this;
    }

    /**
     * Get bay1
     *
     * @return bay1
     **/
    @ApiModelProperty(value = "")
    public String getBay1() {
        return bay1;
    }

    public void setBay1(String bay1) {
        this.bay1 = bay1;
    }

    public MatchScoreBreakdown2019Alliance bay2(String bay2) {
        this.bay2 = bay2;
        return this;
    }

    /**
     * Get bay2
     *
     * @return bay2
     **/
    @ApiModelProperty(value = "")
    public String getBay2() {
        return bay2;
    }

    public void setBay2(String bay2) {
        this.bay2 = bay2;
    }

    public MatchScoreBreakdown2019Alliance bay3(String bay3) {
        this.bay3 = bay3;
        return this;
    }

    /**
     * Get bay3
     *
     * @return bay3
     **/
    @ApiModelProperty(value = "")
    public String getBay3() {
        return bay3;
    }

    public void setBay3(String bay3) {
        this.bay3 = bay3;
    }

    public MatchScoreBreakdown2019Alliance bay4(String bay4) {
        this.bay4 = bay4;
        return this;
    }

    /**
     * Get bay4
     *
     * @return bay4
     **/
    @ApiModelProperty(value = "")
    public String getBay4() {
        return bay4;
    }

    public void setBay4(String bay4) {
        this.bay4 = bay4;
    }

    public MatchScoreBreakdown2019Alliance bay5(String bay5) {
        this.bay5 = bay5;
        return this;
    }

    /**
     * Get bay5
     *
     * @return bay5
     **/
    @ApiModelProperty(value = "")
    public String getBay5() {
        return bay5;
    }

    public void setBay5(String bay5) {
        this.bay5 = bay5;
    }

    public MatchScoreBreakdown2019Alliance bay6(String bay6) {
        this.bay6 = bay6;
        return this;
    }

    /**
     * Get bay6
     *
     * @return bay6
     **/
    @ApiModelProperty(value = "")
    public String getBay6() {
        return bay6;
    }

    public void setBay6(String bay6) {
        this.bay6 = bay6;
    }

    public MatchScoreBreakdown2019Alliance bay7(String bay7) {
        this.bay7 = bay7;
        return this;
    }

    /**
     * Get bay7
     *
     * @return bay7
     **/
    @ApiModelProperty(value = "")
    public String getBay7() {
        return bay7;
    }

    public void setBay7(String bay7) {
        this.bay7 = bay7;
    }

    public MatchScoreBreakdown2019Alliance bay8(String bay8) {
        this.bay8 = bay8;
        return this;
    }

    /**
     * Get bay8
     *
     * @return bay8
     **/
    @ApiModelProperty(value = "")
    public String getBay8() {
        return bay8;
    }

    public void setBay8(String bay8) {
        this.bay8 = bay8;
    }

    public MatchScoreBreakdown2019Alliance cargoPoints(Integer cargoPoints) {
        this.cargoPoints = cargoPoints;
        return this;
    }

    /**
     * Get cargoPoints
     *
     * @return cargoPoints
     **/
    @ApiModelProperty(value = "")
    public Integer getCargoPoints() {
        return cargoPoints;
    }

    public void setCargoPoints(Integer cargoPoints) {
        this.cargoPoints = cargoPoints;
    }

    public MatchScoreBreakdown2019Alliance completeRocketRankingPoint(Boolean completeRocketRankingPoint) {
        this.completeRocketRankingPoint = completeRocketRankingPoint;
        return this;
    }

    /**
     * Get completeRocketRankingPoint
     *
     * @return completeRocketRankingPoint
     **/
    @ApiModelProperty(value = "")
    public Boolean isCompleteRocketRankingPoint() {
        return completeRocketRankingPoint;
    }

    public void setCompleteRocketRankingPoint(Boolean completeRocketRankingPoint) {
        this.completeRocketRankingPoint = completeRocketRankingPoint;
    }

    public MatchScoreBreakdown2019Alliance completedRocketFar(Boolean completedRocketFar) {
        this.completedRocketFar = completedRocketFar;
        return this;
    }

    /**
     * Get completedRocketFar
     *
     * @return completedRocketFar
     **/
    @ApiModelProperty(value = "")
    public Boolean isCompletedRocketFar() {
        return completedRocketFar;
    }

    public void setCompletedRocketFar(Boolean completedRocketFar) {
        this.completedRocketFar = completedRocketFar;
    }

    public MatchScoreBreakdown2019Alliance completedRocketNear(Boolean completedRocketNear) {
        this.completedRocketNear = completedRocketNear;
        return this;
    }

    /**
     * Get completedRocketNear
     *
     * @return completedRocketNear
     **/
    @ApiModelProperty(value = "")
    public Boolean isCompletedRocketNear() {
        return completedRocketNear;
    }

    public void setCompletedRocketNear(Boolean completedRocketNear) {
        this.completedRocketNear = completedRocketNear;
    }

    public MatchScoreBreakdown2019Alliance endgameRobot1(String endgameRobot1) {
        this.endgameRobot1 = endgameRobot1;
        return this;
    }

    /**
     * Get endgameRobot1
     *
     * @return endgameRobot1
     **/
    @ApiModelProperty(value = "")
    public String getEndgameRobot1() {
        return endgameRobot1;
    }

    public void setEndgameRobot1(String endgameRobot1) {
        this.endgameRobot1 = endgameRobot1;
    }

    public MatchScoreBreakdown2019Alliance endgameRobot2(String endgameRobot2) {
        this.endgameRobot2 = endgameRobot2;
        return this;
    }

    /**
     * Get endgameRobot2
     *
     * @return endgameRobot2
     **/
    @ApiModelProperty(value = "")
    public String getEndgameRobot2() {
        return endgameRobot2;
    }

    public void setEndgameRobot2(String endgameRobot2) {
        this.endgameRobot2 = endgameRobot2;
    }

    public MatchScoreBreakdown2019Alliance endgameRobot3(String endgameRobot3) {
        this.endgameRobot3 = endgameRobot3;
        return this;
    }

    /**
     * Get endgameRobot3
     *
     * @return endgameRobot3
     **/
    @ApiModelProperty(value = "")
    public String getEndgameRobot3() {
        return endgameRobot3;
    }

    public void setEndgameRobot3(String endgameRobot3) {
        this.endgameRobot3 = endgameRobot3;
    }

    public MatchScoreBreakdown2019Alliance foulCount(Integer foulCount) {
        this.foulCount = foulCount;
        return this;
    }

    /**
     * Get foulCount
     *
     * @return foulCount
     **/
    @ApiModelProperty(value = "")
    public Integer getFoulCount() {
        return foulCount;
    }

    public void setFoulCount(Integer foulCount) {
        this.foulCount = foulCount;
    }

    public MatchScoreBreakdown2019Alliance foulPoints(Integer foulPoints) {
        this.foulPoints = foulPoints;
        return this;
    }

    /**
     * Get foulPoints
     *
     * @return foulPoints
     **/
    @ApiModelProperty(value = "")
    public Integer getFoulPoints() {
        return foulPoints;
    }

    public void setFoulPoints(Integer foulPoints) {
        this.foulPoints = foulPoints;
    }

    public MatchScoreBreakdown2019Alliance habClimbPoints(Integer habClimbPoints) {
        this.habClimbPoints = habClimbPoints;
        return this;
    }

    /**
     * Get habClimbPoints
     *
     * @return habClimbPoints
     **/
    @ApiModelProperty(value = "")
    public Integer getHabClimbPoints() {
        return habClimbPoints;
    }

    public void setHabClimbPoints(Integer habClimbPoints) {
        this.habClimbPoints = habClimbPoints;
    }

    public MatchScoreBreakdown2019Alliance habDockingRankingPoint(Boolean habDockingRankingPoint) {
        this.habDockingRankingPoint = habDockingRankingPoint;
        return this;
    }

    /**
     * Get habDockingRankingPoint
     *
     * @return habDockingRankingPoint
     **/
    @ApiModelProperty(value = "")
    public Boolean isHabDockingRankingPoint() {
        return habDockingRankingPoint;
    }

    public void setHabDockingRankingPoint(Boolean habDockingRankingPoint) {
        this.habDockingRankingPoint = habDockingRankingPoint;
    }

    public MatchScoreBreakdown2019Alliance habLineRobot1(String habLineRobot1) {
        this.habLineRobot1 = habLineRobot1;
        return this;
    }

    /**
     * Get habLineRobot1
     *
     * @return habLineRobot1
     **/
    @ApiModelProperty(value = "")
    public String getHabLineRobot1() {
        return habLineRobot1;
    }

    public void setHabLineRobot1(String habLineRobot1) {
        this.habLineRobot1 = habLineRobot1;
    }

    public MatchScoreBreakdown2019Alliance habLineRobot2(String habLineRobot2) {
        this.habLineRobot2 = habLineRobot2;
        return this;
    }

    /**
     * Get habLineRobot2
     *
     * @return habLineRobot2
     **/
    @ApiModelProperty(value = "")
    public String getHabLineRobot2() {
        return habLineRobot2;
    }

    public void setHabLineRobot2(String habLineRobot2) {
        this.habLineRobot2 = habLineRobot2;
    }

    public MatchScoreBreakdown2019Alliance habLineRobot3(String habLineRobot3) {
        this.habLineRobot3 = habLineRobot3;
        return this;
    }

    /**
     * Get habLineRobot3
     *
     * @return habLineRobot3
     **/
    @ApiModelProperty(value = "")
    public String getHabLineRobot3() {
        return habLineRobot3;
    }

    public void setHabLineRobot3(String habLineRobot3) {
        this.habLineRobot3 = habLineRobot3;
    }

    public MatchScoreBreakdown2019Alliance hatchPanelPoints(Integer hatchPanelPoints) {
        this.hatchPanelPoints = hatchPanelPoints;
        return this;
    }

    /**
     * Get hatchPanelPoints
     *
     * @return hatchPanelPoints
     **/
    @ApiModelProperty(value = "")
    public Integer getHatchPanelPoints() {
        return hatchPanelPoints;
    }

    public void setHatchPanelPoints(Integer hatchPanelPoints) {
        this.hatchPanelPoints = hatchPanelPoints;
    }

    public MatchScoreBreakdown2019Alliance lowLeftRocketFar(String lowLeftRocketFar) {
        this.lowLeftRocketFar = lowLeftRocketFar;
        return this;
    }

    /**
     * Get lowLeftRocketFar
     *
     * @return lowLeftRocketFar
     **/
    @ApiModelProperty(value = "")
    public String getLowLeftRocketFar() {
        return lowLeftRocketFar;
    }

    public void setLowLeftRocketFar(String lowLeftRocketFar) {
        this.lowLeftRocketFar = lowLeftRocketFar;
    }

    public MatchScoreBreakdown2019Alliance lowLeftRocketNear(String lowLeftRocketNear) {
        this.lowLeftRocketNear = lowLeftRocketNear;
        return this;
    }

    /**
     * Get lowLeftRocketNear
     *
     * @return lowLeftRocketNear
     **/
    @ApiModelProperty(value = "")
    public String getLowLeftRocketNear() {
        return lowLeftRocketNear;
    }

    public void setLowLeftRocketNear(String lowLeftRocketNear) {
        this.lowLeftRocketNear = lowLeftRocketNear;
    }

    public MatchScoreBreakdown2019Alliance lowRightRocketFar(String lowRightRocketFar) {
        this.lowRightRocketFar = lowRightRocketFar;
        return this;
    }

    /**
     * Get lowRightRocketFar
     *
     * @return lowRightRocketFar
     **/
    @ApiModelProperty(value = "")
    public String getLowRightRocketFar() {
        return lowRightRocketFar;
    }

    public void setLowRightRocketFar(String lowRightRocketFar) {
        this.lowRightRocketFar = lowRightRocketFar;
    }

    public MatchScoreBreakdown2019Alliance lowRightRocketNear(String lowRightRocketNear) {
        this.lowRightRocketNear = lowRightRocketNear;
        return this;
    }

    /**
     * Get lowRightRocketNear
     *
     * @return lowRightRocketNear
     **/
    @ApiModelProperty(value = "")
    public String getLowRightRocketNear() {
        return lowRightRocketNear;
    }

    public void setLowRightRocketNear(String lowRightRocketNear) {
        this.lowRightRocketNear = lowRightRocketNear;
    }

    public MatchScoreBreakdown2019Alliance midLeftRocketFar(String midLeftRocketFar) {
        this.midLeftRocketFar = midLeftRocketFar;
        return this;
    }

    /**
     * Get midLeftRocketFar
     *
     * @return midLeftRocketFar
     **/
    @ApiModelProperty(value = "")
    public String getMidLeftRocketFar() {
        return midLeftRocketFar;
    }

    public void setMidLeftRocketFar(String midLeftRocketFar) {
        this.midLeftRocketFar = midLeftRocketFar;
    }

    public MatchScoreBreakdown2019Alliance midLeftRocketNear(String midLeftRocketNear) {
        this.midLeftRocketNear = midLeftRocketNear;
        return this;
    }

    /**
     * Get midLeftRocketNear
     *
     * @return midLeftRocketNear
     **/
    @ApiModelProperty(value = "")
    public String getMidLeftRocketNear() {
        return midLeftRocketNear;
    }

    public void setMidLeftRocketNear(String midLeftRocketNear) {
        this.midLeftRocketNear = midLeftRocketNear;
    }

    public MatchScoreBreakdown2019Alliance midRightRocketFar(String midRightRocketFar) {
        this.midRightRocketFar = midRightRocketFar;
        return this;
    }

    /**
     * Get midRightRocketFar
     *
     * @return midRightRocketFar
     **/
    @ApiModelProperty(value = "")
    public String getMidRightRocketFar() {
        return midRightRocketFar;
    }

    public void setMidRightRocketFar(String midRightRocketFar) {
        this.midRightRocketFar = midRightRocketFar;
    }

    public MatchScoreBreakdown2019Alliance midRightRocketNear(String midRightRocketNear) {
        this.midRightRocketNear = midRightRocketNear;
        return this;
    }

    /**
     * Get midRightRocketNear
     *
     * @return midRightRocketNear
     **/
    @ApiModelProperty(value = "")
    public String getMidRightRocketNear() {
        return midRightRocketNear;
    }

    public void setMidRightRocketNear(String midRightRocketNear) {
        this.midRightRocketNear = midRightRocketNear;
    }

    public MatchScoreBreakdown2019Alliance preMatchBay1(String preMatchBay1) {
        this.preMatchBay1 = preMatchBay1;
        return this;
    }

    /**
     * Get preMatchBay1
     *
     * @return preMatchBay1
     **/
    @ApiModelProperty(value = "")
    public String getPreMatchBay1() {
        return preMatchBay1;
    }

    public void setPreMatchBay1(String preMatchBay1) {
        this.preMatchBay1 = preMatchBay1;
    }

    public MatchScoreBreakdown2019Alliance preMatchBay2(String preMatchBay2) {
        this.preMatchBay2 = preMatchBay2;
        return this;
    }

    /**
     * Get preMatchBay2
     *
     * @return preMatchBay2
     **/
    @ApiModelProperty(value = "")
    public String getPreMatchBay2() {
        return preMatchBay2;
    }

    public void setPreMatchBay2(String preMatchBay2) {
        this.preMatchBay2 = preMatchBay2;
    }

    public MatchScoreBreakdown2019Alliance preMatchBay3(String preMatchBay3) {
        this.preMatchBay3 = preMatchBay3;
        return this;
    }

    /**
     * Get preMatchBay3
     *
     * @return preMatchBay3
     **/
    @ApiModelProperty(value = "")
    public String getPreMatchBay3() {
        return preMatchBay3;
    }

    public void setPreMatchBay3(String preMatchBay3) {
        this.preMatchBay3 = preMatchBay3;
    }

    public MatchScoreBreakdown2019Alliance preMatchBay6(String preMatchBay6) {
        this.preMatchBay6 = preMatchBay6;
        return this;
    }

    /**
     * Get preMatchBay6
     *
     * @return preMatchBay6
     **/
    @ApiModelProperty(value = "")
    public String getPreMatchBay6() {
        return preMatchBay6;
    }

    public void setPreMatchBay6(String preMatchBay6) {
        this.preMatchBay6 = preMatchBay6;
    }

    public MatchScoreBreakdown2019Alliance preMatchBay7(String preMatchBay7) {
        this.preMatchBay7 = preMatchBay7;
        return this;
    }

    /**
     * Get preMatchBay7
     *
     * @return preMatchBay7
     **/
    @ApiModelProperty(value = "")
    public String getPreMatchBay7() {
        return preMatchBay7;
    }

    public void setPreMatchBay7(String preMatchBay7) {
        this.preMatchBay7 = preMatchBay7;
    }

    public MatchScoreBreakdown2019Alliance preMatchBay8(String preMatchBay8) {
        this.preMatchBay8 = preMatchBay8;
        return this;
    }

    /**
     * Get preMatchBay8
     *
     * @return preMatchBay8
     **/
    @ApiModelProperty(value = "")
    public String getPreMatchBay8() {
        return preMatchBay8;
    }

    public void setPreMatchBay8(String preMatchBay8) {
        this.preMatchBay8 = preMatchBay8;
    }

    public MatchScoreBreakdown2019Alliance preMatchLevelRobot1(String preMatchLevelRobot1) {
        this.preMatchLevelRobot1 = preMatchLevelRobot1;
        return this;
    }

    /**
     * Get preMatchLevelRobot1
     *
     * @return preMatchLevelRobot1
     **/
    @ApiModelProperty(value = "")
    public String getPreMatchLevelRobot1() {
        return preMatchLevelRobot1;
    }

    public void setPreMatchLevelRobot1(String preMatchLevelRobot1) {
        this.preMatchLevelRobot1 = preMatchLevelRobot1;
    }

    public MatchScoreBreakdown2019Alliance preMatchLevelRobot2(String preMatchLevelRobot2) {
        this.preMatchLevelRobot2 = preMatchLevelRobot2;
        return this;
    }

    /**
     * Get preMatchLevelRobot2
     *
     * @return preMatchLevelRobot2
     **/
    @ApiModelProperty(value = "")
    public String getPreMatchLevelRobot2() {
        return preMatchLevelRobot2;
    }

    public void setPreMatchLevelRobot2(String preMatchLevelRobot2) {
        this.preMatchLevelRobot2 = preMatchLevelRobot2;
    }

    public MatchScoreBreakdown2019Alliance preMatchLevelRobot3(String preMatchLevelRobot3) {
        this.preMatchLevelRobot3 = preMatchLevelRobot3;
        return this;
    }

    /**
     * Get preMatchLevelRobot3
     *
     * @return preMatchLevelRobot3
     **/
    @ApiModelProperty(value = "")
    public String getPreMatchLevelRobot3() {
        return preMatchLevelRobot3;
    }

    public void setPreMatchLevelRobot3(String preMatchLevelRobot3) {
        this.preMatchLevelRobot3 = preMatchLevelRobot3;
    }

    public MatchScoreBreakdown2019Alliance rp(Integer rp) {
        this.rp = rp;
        return this;
    }

    /**
     * Get rp
     *
     * @return rp
     **/
    @ApiModelProperty(value = "")
    public Integer getRp() {
        return rp;
    }

    public void setRp(Integer rp) {
        this.rp = rp;
    }

    public MatchScoreBreakdown2019Alliance sandStormBonusPoints(Integer sandStormBonusPoints) {
        this.sandStormBonusPoints = sandStormBonusPoints;
        return this;
    }

    /**
     * Get sandStormBonusPoints
     *
     * @return sandStormBonusPoints
     **/
    @ApiModelProperty(value = "")
    public Integer getSandStormBonusPoints() {
        return sandStormBonusPoints;
    }

    public void setSandStormBonusPoints(Integer sandStormBonusPoints) {
        this.sandStormBonusPoints = sandStormBonusPoints;
    }

    public MatchScoreBreakdown2019Alliance techFoulCount(Integer techFoulCount) {
        this.techFoulCount = techFoulCount;
        return this;
    }

    /**
     * Get techFoulCount
     *
     * @return techFoulCount
     **/
    @ApiModelProperty(value = "")
    public Integer getTechFoulCount() {
        return techFoulCount;
    }

    public void setTechFoulCount(Integer techFoulCount) {
        this.techFoulCount = techFoulCount;
    }

    public MatchScoreBreakdown2019Alliance teleopPoints(Integer teleopPoints) {
        this.teleopPoints = teleopPoints;
        return this;
    }

    /**
     * Get teleopPoints
     *
     * @return teleopPoints
     **/
    @ApiModelProperty(value = "")
    public Integer getTeleopPoints() {
        return teleopPoints;
    }

    public void setTeleopPoints(Integer teleopPoints) {
        this.teleopPoints = teleopPoints;
    }

    public MatchScoreBreakdown2019Alliance topLeftRocketFar(String topLeftRocketFar) {
        this.topLeftRocketFar = topLeftRocketFar;
        return this;
    }

    /**
     * Get topLeftRocketFar
     *
     * @return topLeftRocketFar
     **/
    @ApiModelProperty(value = "")
    public String getTopLeftRocketFar() {
        return topLeftRocketFar;
    }

    public void setTopLeftRocketFar(String topLeftRocketFar) {
        this.topLeftRocketFar = topLeftRocketFar;
    }

    public MatchScoreBreakdown2019Alliance topLeftRocketNear(String topLeftRocketNear) {
        this.topLeftRocketNear = topLeftRocketNear;
        return this;
    }

    /**
     * Get topLeftRocketNear
     *
     * @return topLeftRocketNear
     **/
    @ApiModelProperty(value = "")
    public String getTopLeftRocketNear() {
        return topLeftRocketNear;
    }

    public void setTopLeftRocketNear(String topLeftRocketNear) {
        this.topLeftRocketNear = topLeftRocketNear;
    }

    public MatchScoreBreakdown2019Alliance topRightRocketFar(String topRightRocketFar) {
        this.topRightRocketFar = topRightRocketFar;
        return this;
    }

    /**
     * Get topRightRocketFar
     *
     * @return topRightRocketFar
     **/
    @ApiModelProperty(value = "")
    public String getTopRightRocketFar() {
        return topRightRocketFar;
    }

    public void setTopRightRocketFar(String topRightRocketFar) {
        this.topRightRocketFar = topRightRocketFar;
    }

    public MatchScoreBreakdown2019Alliance topRightRocketNear(String topRightRocketNear) {
        this.topRightRocketNear = topRightRocketNear;
        return this;
    }

    /**
     * Get topRightRocketNear
     *
     * @return topRightRocketNear
     **/
    @ApiModelProperty(value = "")
    public String getTopRightRocketNear() {
        return topRightRocketNear;
    }

    public void setTopRightRocketNear(String topRightRocketNear) {
        this.topRightRocketNear = topRightRocketNear;
    }

    public MatchScoreBreakdown2019Alliance totalPoints(Integer totalPoints) {
        this.totalPoints = totalPoints;
        return this;
    }

    /**
     * Get totalPoints
     *
     * @return totalPoints
     **/
    @ApiModelProperty(value = "")
    public Integer getTotalPoints() {
        return totalPoints;
    }

    public void setTotalPoints(Integer totalPoints) {
        this.totalPoints = totalPoints;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MatchScoreBreakdown2019Alliance matchScoreBreakdown2019Alliance = (MatchScoreBreakdown2019Alliance) o;
        return Objects.equals(this.adjustPoints, matchScoreBreakdown2019Alliance.adjustPoints) &&
                Objects.equals(this.autoPoints, matchScoreBreakdown2019Alliance.autoPoints) &&
                Objects.equals(this.bay1, matchScoreBreakdown2019Alliance.bay1) &&
                Objects.equals(this.bay2, matchScoreBreakdown2019Alliance.bay2) &&
                Objects.equals(this.bay3, matchScoreBreakdown2019Alliance.bay3) &&
                Objects.equals(this.bay4, matchScoreBreakdown2019Alliance.bay4) &&
                Objects.equals(this.bay5, matchScoreBreakdown2019Alliance.bay5) &&
                Objects.equals(this.bay6, matchScoreBreakdown2019Alliance.bay6) &&
                Objects.equals(this.bay7, matchScoreBreakdown2019Alliance.bay7) &&
                Objects.equals(this.bay8, matchScoreBreakdown2019Alliance.bay8) &&
                Objects.equals(this.cargoPoints, matchScoreBreakdown2019Alliance.cargoPoints) &&
                Objects.equals(this.completeRocketRankingPoint, matchScoreBreakdown2019Alliance.completeRocketRankingPoint) &&
                Objects.equals(this.completedRocketFar, matchScoreBreakdown2019Alliance.completedRocketFar) &&
                Objects.equals(this.completedRocketNear, matchScoreBreakdown2019Alliance.completedRocketNear) &&
                Objects.equals(this.endgameRobot1, matchScoreBreakdown2019Alliance.endgameRobot1) &&
                Objects.equals(this.endgameRobot2, matchScoreBreakdown2019Alliance.endgameRobot2) &&
                Objects.equals(this.endgameRobot3, matchScoreBreakdown2019Alliance.endgameRobot3) &&
                Objects.equals(this.foulCount, matchScoreBreakdown2019Alliance.foulCount) &&
                Objects.equals(this.foulPoints, matchScoreBreakdown2019Alliance.foulPoints) &&
                Objects.equals(this.habClimbPoints, matchScoreBreakdown2019Alliance.habClimbPoints) &&
                Objects.equals(this.habDockingRankingPoint, matchScoreBreakdown2019Alliance.habDockingRankingPoint) &&
                Objects.equals(this.habLineRobot1, matchScoreBreakdown2019Alliance.habLineRobot1) &&
                Objects.equals(this.habLineRobot2, matchScoreBreakdown2019Alliance.habLineRobot2) &&
                Objects.equals(this.habLineRobot3, matchScoreBreakdown2019Alliance.habLineRobot3) &&
                Objects.equals(this.hatchPanelPoints, matchScoreBreakdown2019Alliance.hatchPanelPoints) &&
                Objects.equals(this.lowLeftRocketFar, matchScoreBreakdown2019Alliance.lowLeftRocketFar) &&
                Objects.equals(this.lowLeftRocketNear, matchScoreBreakdown2019Alliance.lowLeftRocketNear) &&
                Objects.equals(this.lowRightRocketFar, matchScoreBreakdown2019Alliance.lowRightRocketFar) &&
                Objects.equals(this.lowRightRocketNear, matchScoreBreakdown2019Alliance.lowRightRocketNear) &&
                Objects.equals(this.midLeftRocketFar, matchScoreBreakdown2019Alliance.midLeftRocketFar) &&
                Objects.equals(this.midLeftRocketNear, matchScoreBreakdown2019Alliance.midLeftRocketNear) &&
                Objects.equals(this.midRightRocketFar, matchScoreBreakdown2019Alliance.midRightRocketFar) &&
                Objects.equals(this.midRightRocketNear, matchScoreBreakdown2019Alliance.midRightRocketNear) &&
                Objects.equals(this.preMatchBay1, matchScoreBreakdown2019Alliance.preMatchBay1) &&
                Objects.equals(this.preMatchBay2, matchScoreBreakdown2019Alliance.preMatchBay2) &&
                Objects.equals(this.preMatchBay3, matchScoreBreakdown2019Alliance.preMatchBay3) &&
                Objects.equals(this.preMatchBay6, matchScoreBreakdown2019Alliance.preMatchBay6) &&
                Objects.equals(this.preMatchBay7, matchScoreBreakdown2019Alliance.preMatchBay7) &&
                Objects.equals(this.preMatchBay8, matchScoreBreakdown2019Alliance.preMatchBay8) &&
                Objects.equals(this.preMatchLevelRobot1, matchScoreBreakdown2019Alliance.preMatchLevelRobot1) &&
                Objects.equals(this.preMatchLevelRobot2, matchScoreBreakdown2019Alliance.preMatchLevelRobot2) &&
                Objects.equals(this.preMatchLevelRobot3, matchScoreBreakdown2019Alliance.preMatchLevelRobot3) &&
                Objects.equals(this.rp, matchScoreBreakdown2019Alliance.rp) &&
                Objects.equals(this.sandStormBonusPoints, matchScoreBreakdown2019Alliance.sandStormBonusPoints) &&
                Objects.equals(this.techFoulCount, matchScoreBreakdown2019Alliance.techFoulCount) &&
                Objects.equals(this.teleopPoints, matchScoreBreakdown2019Alliance.teleopPoints) &&
                Objects.equals(this.topLeftRocketFar, matchScoreBreakdown2019Alliance.topLeftRocketFar) &&
                Objects.equals(this.topLeftRocketNear, matchScoreBreakdown2019Alliance.topLeftRocketNear) &&
                Objects.equals(this.topRightRocketFar, matchScoreBreakdown2019Alliance.topRightRocketFar) &&
                Objects.equals(this.topRightRocketNear, matchScoreBreakdown2019Alliance.topRightRocketNear) &&
                Objects.equals(this.totalPoints, matchScoreBreakdown2019Alliance.totalPoints);
    }

    @Override
    public int hashCode() {
        return Objects.hash(adjustPoints, autoPoints, bay1, bay2, bay3, bay4, bay5, bay6, bay7, bay8, cargoPoints, completeRocketRankingPoint, completedRocketFar, completedRocketNear, endgameRobot1, endgameRobot2, endgameRobot3, foulCount, foulPoints, habClimbPoints, habDockingRankingPoint, habLineRobot1, habLineRobot2, habLineRobot3, hatchPanelPoints, lowLeftRocketFar, lowLeftRocketNear, lowRightRocketFar, lowRightRocketNear, midLeftRocketFar, midLeftRocketNear, midRightRocketFar, midRightRocketNear, preMatchBay1, preMatchBay2, preMatchBay3, preMatchBay6, preMatchBay7, preMatchBay8, preMatchLevelRobot1, preMatchLevelRobot2, preMatchLevelRobot3, rp, sandStormBonusPoints, techFoulCount, teleopPoints, topLeftRocketFar, topLeftRocketNear, topRightRocketFar, topRightRocketNear, totalPoints);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MatchScoreBreakdown2019Alliance {\n");

        sb.append("    adjustPoints: ").append(toIndentedString(adjustPoints)).append("\n");
        sb.append("    autoPoints: ").append(toIndentedString(autoPoints)).append("\n");
        sb.append("    bay1: ").append(toIndentedString(bay1)).append("\n");
        sb.append("    bay2: ").append(toIndentedString(bay2)).append("\n");
        sb.append("    bay3: ").append(toIndentedString(bay3)).append("\n");
        sb.append("    bay4: ").append(toIndentedString(bay4)).append("\n");
        sb.append("    bay5: ").append(toIndentedString(bay5)).append("\n");
        sb.append("    bay6: ").append(toIndentedString(bay6)).append("\n");
        sb.append("    bay7: ").append(toIndentedString(bay7)).append("\n");
        sb.append("    bay8: ").append(toIndentedString(bay8)).append("\n");
        sb.append("    cargoPoints: ").append(toIndentedString(cargoPoints)).append("\n");
        sb.append("    completeRocketRankingPoint: ").append(toIndentedString(completeRocketRankingPoint)).append("\n");
        sb.append("    completedRocketFar: ").append(toIndentedString(completedRocketFar)).append("\n");
        sb.append("    completedRocketNear: ").append(toIndentedString(completedRocketNear)).append("\n");
        sb.append("    endgameRobot1: ").append(toIndentedString(endgameRobot1)).append("\n");
        sb.append("    endgameRobot2: ").append(toIndentedString(endgameRobot2)).append("\n");
        sb.append("    endgameRobot3: ").append(toIndentedString(endgameRobot3)).append("\n");
        sb.append("    foulCount: ").append(toIndentedString(foulCount)).append("\n");
        sb.append("    foulPoints: ").append(toIndentedString(foulPoints)).append("\n");
        sb.append("    habClimbPoints: ").append(toIndentedString(habClimbPoints)).append("\n");
        sb.append("    habDockingRankingPoint: ").append(toIndentedString(habDockingRankingPoint)).append("\n");
        sb.append("    habLineRobot1: ").append(toIndentedString(habLineRobot1)).append("\n");
        sb.append("    habLineRobot2: ").append(toIndentedString(habLineRobot2)).append("\n");
        sb.append("    habLineRobot3: ").append(toIndentedString(habLineRobot3)).append("\n");
        sb.append("    hatchPanelPoints: ").append(toIndentedString(hatchPanelPoints)).append("\n");
        sb.append("    lowLeftRocketFar: ").append(toIndentedString(lowLeftRocketFar)).append("\n");
        sb.append("    lowLeftRocketNear: ").append(toIndentedString(lowLeftRocketNear)).append("\n");
        sb.append("    lowRightRocketFar: ").append(toIndentedString(lowRightRocketFar)).append("\n");
        sb.append("    lowRightRocketNear: ").append(toIndentedString(lowRightRocketNear)).append("\n");
        sb.append("    midLeftRocketFar: ").append(toIndentedString(midLeftRocketFar)).append("\n");
        sb.append("    midLeftRocketNear: ").append(toIndentedString(midLeftRocketNear)).append("\n");
        sb.append("    midRightRocketFar: ").append(toIndentedString(midRightRocketFar)).append("\n");
        sb.append("    midRightRocketNear: ").append(toIndentedString(midRightRocketNear)).append("\n");
        sb.append("    preMatchBay1: ").append(toIndentedString(preMatchBay1)).append("\n");
        sb.append("    preMatchBay2: ").append(toIndentedString(preMatchBay2)).append("\n");
        sb.append("    preMatchBay3: ").append(toIndentedString(preMatchBay3)).append("\n");
        sb.append("    preMatchBay6: ").append(toIndentedString(preMatchBay6)).append("\n");
        sb.append("    preMatchBay7: ").append(toIndentedString(preMatchBay7)).append("\n");
        sb.append("    preMatchBay8: ").append(toIndentedString(preMatchBay8)).append("\n");
        sb.append("    preMatchLevelRobot1: ").append(toIndentedString(preMatchLevelRobot1)).append("\n");
        sb.append("    preMatchLevelRobot2: ").append(toIndentedString(preMatchLevelRobot2)).append("\n");
        sb.append("    preMatchLevelRobot3: ").append(toIndentedString(preMatchLevelRobot3)).append("\n");
        sb.append("    rp: ").append(toIndentedString(rp)).append("\n");
        sb.append("    sandStormBonusPoints: ").append(toIndentedString(sandStormBonusPoints)).append("\n");
        sb.append("    techFoulCount: ").append(toIndentedString(techFoulCount)).append("\n");
        sb.append("    teleopPoints: ").append(toIndentedString(teleopPoints)).append("\n");
        sb.append("    topLeftRocketFar: ").append(toIndentedString(topLeftRocketFar)).append("\n");
        sb.append("    topLeftRocketNear: ").append(toIndentedString(topLeftRocketNear)).append("\n");
        sb.append("    topRightRocketFar: ").append(toIndentedString(topRightRocketFar)).append("\n");
        sb.append("    topRightRocketNear: ").append(toIndentedString(topRightRocketNear)).append("\n");
        sb.append("    totalPoints: ").append(toIndentedString(totalPoints)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

