/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MatchVideos
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-01T17:18:29.994708-05:00[US/Eastern]")
public class MatchVideos {
  @SerializedName("type")
  private String type = null;

  @SerializedName("key")
  private String key = null;

  public MatchVideos type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Can be one of &#x27;youtube&#x27; or &#x27;tba&#x27;
   * @return type
  **/
  @Schema(description = "Can be one of 'youtube' or 'tba'")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public MatchVideos key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Unique key representing this video
   * @return key
  **/
  @Schema(description = "Unique key representing this video")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchVideos matchVideos = (MatchVideos) o;
    return Objects.equals(this.type, matchVideos.type) &&
        Objects.equals(this.key, matchVideos.key);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, key);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchVideos {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
