/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.MatchScoreBreakdown2022Alliance;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * See the 2022 FMS API documentation for a description of each value. https://frc-api-docs.firstinspires.org
 */
@Schema(description = "See the 2022 FMS API documentation for a description of each value. https://frc-api-docs.firstinspires.org")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-26T16:01:43.676Z[GMT]")
public class MatchScoreBreakdown2022 {
  @SerializedName("blue")
  private MatchScoreBreakdown2022Alliance blue = null;

  @SerializedName("red")
  private MatchScoreBreakdown2022Alliance red = null;

  public MatchScoreBreakdown2022 blue(MatchScoreBreakdown2022Alliance blue) {
    this.blue = blue;
    return this;
  }

   /**
   * Get blue
   * @return blue
  **/
  @Schema(description = "")
  public MatchScoreBreakdown2022Alliance getBlue() {
    return blue;
  }

  public void setBlue(MatchScoreBreakdown2022Alliance blue) {
    this.blue = blue;
  }

  public MatchScoreBreakdown2022 red(MatchScoreBreakdown2022Alliance red) {
    this.red = red;
    return this;
  }

   /**
   * Get red
   * @return red
  **/
  @Schema(description = "")
  public MatchScoreBreakdown2022Alliance getRed() {
    return red;
  }

  public void setRed(MatchScoreBreakdown2022Alliance red) {
    this.red = red;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchScoreBreakdown2022 matchScoreBreakdown2022 = (MatchScoreBreakdown2022) o;
    return Objects.equals(this.blue, matchScoreBreakdown2022.blue) &&
        Objects.equals(this.red, matchScoreBreakdown2022.red);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blue, red);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchScoreBreakdown2022 {\n");
    
    sb.append("    blue: ").append(toIndentedString(blue)).append("\n");
    sb.append("    red: ").append(toIndentedString(red)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
