/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MatchScoreBreakdown2020Alliance
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-26T16:01:43.676Z[GMT]")
public class MatchScoreBreakdown2020Alliance {
  @SerializedName("initLineRobot1")
  private String initLineRobot1 = null;

  @SerializedName("endgameRobot1")
  private String endgameRobot1 = null;

  @SerializedName("initLineRobot2")
  private String initLineRobot2 = null;

  @SerializedName("endgameRobot2")
  private String endgameRobot2 = null;

  @SerializedName("initLineRobot3")
  private String initLineRobot3 = null;

  @SerializedName("endgameRobot3")
  private String endgameRobot3 = null;

  @SerializedName("autoCellsBottom")
  private Integer autoCellsBottom = null;

  @SerializedName("autoCellsOuter")
  private Integer autoCellsOuter = null;

  @SerializedName("autoCellsInner")
  private Integer autoCellsInner = null;

  @SerializedName("teleopCellsBottom")
  private Integer teleopCellsBottom = null;

  @SerializedName("teleopCellsOuter")
  private Integer teleopCellsOuter = null;

  @SerializedName("teleopCellsInner")
  private Integer teleopCellsInner = null;

  @SerializedName("stage1Activated")
  private Boolean stage1Activated = null;

  @SerializedName("stage2Activated")
  private Boolean stage2Activated = null;

  @SerializedName("stage3Activated")
  private Boolean stage3Activated = null;

  @SerializedName("stage3TargetColor")
  private String stage3TargetColor = null;

  @SerializedName("endgameRungIsLevel")
  private String endgameRungIsLevel = null;

  @SerializedName("autoInitLinePoints")
  private Integer autoInitLinePoints = null;

  @SerializedName("autoCellPoints")
  private Integer autoCellPoints = null;

  @SerializedName("autoPoints")
  private Integer autoPoints = null;

  @SerializedName("teleopCellPoints")
  private Integer teleopCellPoints = null;

  @SerializedName("controlPanelPoints")
  private Integer controlPanelPoints = null;

  @SerializedName("endgamePoints")
  private Integer endgamePoints = null;

  @SerializedName("teleopPoints")
  private Integer teleopPoints = null;

  @SerializedName("shieldOperationalRankingPoint")
  private Boolean shieldOperationalRankingPoint = null;

  @SerializedName("shieldEnergizedRankingPoint")
  private Boolean shieldEnergizedRankingPoint = null;

  @SerializedName("tba_shieldEnergizedRankingPointFromFoul")
  private Boolean tbaShieldEnergizedRankingPointFromFoul = null;

  @SerializedName("tba_numRobotsHanging")
  private Integer tbaNumRobotsHanging = null;

  @SerializedName("foulCount")
  private Integer foulCount = null;

  @SerializedName("techFoulCount")
  private Integer techFoulCount = null;

  @SerializedName("adjustPoints")
  private Integer adjustPoints = null;

  @SerializedName("foulPoints")
  private Integer foulPoints = null;

  @SerializedName("rp")
  private Integer rp = null;

  @SerializedName("totalPoints")
  private Integer totalPoints = null;

  public MatchScoreBreakdown2020Alliance initLineRobot1(String initLineRobot1) {
    this.initLineRobot1 = initLineRobot1;
    return this;
  }

   /**
   * Get initLineRobot1
   * @return initLineRobot1
  **/
  @Schema(description = "")
  public String getInitLineRobot1() {
    return initLineRobot1;
  }

  public void setInitLineRobot1(String initLineRobot1) {
    this.initLineRobot1 = initLineRobot1;
  }

  public MatchScoreBreakdown2020Alliance endgameRobot1(String endgameRobot1) {
    this.endgameRobot1 = endgameRobot1;
    return this;
  }

   /**
   * Get endgameRobot1
   * @return endgameRobot1
  **/
  @Schema(description = "")
  public String getEndgameRobot1() {
    return endgameRobot1;
  }

  public void setEndgameRobot1(String endgameRobot1) {
    this.endgameRobot1 = endgameRobot1;
  }

  public MatchScoreBreakdown2020Alliance initLineRobot2(String initLineRobot2) {
    this.initLineRobot2 = initLineRobot2;
    return this;
  }

   /**
   * Get initLineRobot2
   * @return initLineRobot2
  **/
  @Schema(description = "")
  public String getInitLineRobot2() {
    return initLineRobot2;
  }

  public void setInitLineRobot2(String initLineRobot2) {
    this.initLineRobot2 = initLineRobot2;
  }

  public MatchScoreBreakdown2020Alliance endgameRobot2(String endgameRobot2) {
    this.endgameRobot2 = endgameRobot2;
    return this;
  }

   /**
   * Get endgameRobot2
   * @return endgameRobot2
  **/
  @Schema(description = "")
  public String getEndgameRobot2() {
    return endgameRobot2;
  }

  public void setEndgameRobot2(String endgameRobot2) {
    this.endgameRobot2 = endgameRobot2;
  }

  public MatchScoreBreakdown2020Alliance initLineRobot3(String initLineRobot3) {
    this.initLineRobot3 = initLineRobot3;
    return this;
  }

   /**
   * Get initLineRobot3
   * @return initLineRobot3
  **/
  @Schema(description = "")
  public String getInitLineRobot3() {
    return initLineRobot3;
  }

  public void setInitLineRobot3(String initLineRobot3) {
    this.initLineRobot3 = initLineRobot3;
  }

  public MatchScoreBreakdown2020Alliance endgameRobot3(String endgameRobot3) {
    this.endgameRobot3 = endgameRobot3;
    return this;
  }

   /**
   * Get endgameRobot3
   * @return endgameRobot3
  **/
  @Schema(description = "")
  public String getEndgameRobot3() {
    return endgameRobot3;
  }

  public void setEndgameRobot3(String endgameRobot3) {
    this.endgameRobot3 = endgameRobot3;
  }

  public MatchScoreBreakdown2020Alliance autoCellsBottom(Integer autoCellsBottom) {
    this.autoCellsBottom = autoCellsBottom;
    return this;
  }

   /**
   * Get autoCellsBottom
   * @return autoCellsBottom
  **/
  @Schema(description = "")
  public Integer getAutoCellsBottom() {
    return autoCellsBottom;
  }

  public void setAutoCellsBottom(Integer autoCellsBottom) {
    this.autoCellsBottom = autoCellsBottom;
  }

  public MatchScoreBreakdown2020Alliance autoCellsOuter(Integer autoCellsOuter) {
    this.autoCellsOuter = autoCellsOuter;
    return this;
  }

   /**
   * Get autoCellsOuter
   * @return autoCellsOuter
  **/
  @Schema(description = "")
  public Integer getAutoCellsOuter() {
    return autoCellsOuter;
  }

  public void setAutoCellsOuter(Integer autoCellsOuter) {
    this.autoCellsOuter = autoCellsOuter;
  }

  public MatchScoreBreakdown2020Alliance autoCellsInner(Integer autoCellsInner) {
    this.autoCellsInner = autoCellsInner;
    return this;
  }

   /**
   * Get autoCellsInner
   * @return autoCellsInner
  **/
  @Schema(description = "")
  public Integer getAutoCellsInner() {
    return autoCellsInner;
  }

  public void setAutoCellsInner(Integer autoCellsInner) {
    this.autoCellsInner = autoCellsInner;
  }

  public MatchScoreBreakdown2020Alliance teleopCellsBottom(Integer teleopCellsBottom) {
    this.teleopCellsBottom = teleopCellsBottom;
    return this;
  }

   /**
   * Get teleopCellsBottom
   * @return teleopCellsBottom
  **/
  @Schema(description = "")
  public Integer getTeleopCellsBottom() {
    return teleopCellsBottom;
  }

  public void setTeleopCellsBottom(Integer teleopCellsBottom) {
    this.teleopCellsBottom = teleopCellsBottom;
  }

  public MatchScoreBreakdown2020Alliance teleopCellsOuter(Integer teleopCellsOuter) {
    this.teleopCellsOuter = teleopCellsOuter;
    return this;
  }

   /**
   * Get teleopCellsOuter
   * @return teleopCellsOuter
  **/
  @Schema(description = "")
  public Integer getTeleopCellsOuter() {
    return teleopCellsOuter;
  }

  public void setTeleopCellsOuter(Integer teleopCellsOuter) {
    this.teleopCellsOuter = teleopCellsOuter;
  }

  public MatchScoreBreakdown2020Alliance teleopCellsInner(Integer teleopCellsInner) {
    this.teleopCellsInner = teleopCellsInner;
    return this;
  }

   /**
   * Get teleopCellsInner
   * @return teleopCellsInner
  **/
  @Schema(description = "")
  public Integer getTeleopCellsInner() {
    return teleopCellsInner;
  }

  public void setTeleopCellsInner(Integer teleopCellsInner) {
    this.teleopCellsInner = teleopCellsInner;
  }

  public MatchScoreBreakdown2020Alliance stage1Activated(Boolean stage1Activated) {
    this.stage1Activated = stage1Activated;
    return this;
  }

   /**
   * Get stage1Activated
   * @return stage1Activated
  **/
  @Schema(description = "")
  public Boolean isStage1Activated() {
    return stage1Activated;
  }

  public void setStage1Activated(Boolean stage1Activated) {
    this.stage1Activated = stage1Activated;
  }

  public MatchScoreBreakdown2020Alliance stage2Activated(Boolean stage2Activated) {
    this.stage2Activated = stage2Activated;
    return this;
  }

   /**
   * Get stage2Activated
   * @return stage2Activated
  **/
  @Schema(description = "")
  public Boolean isStage2Activated() {
    return stage2Activated;
  }

  public void setStage2Activated(Boolean stage2Activated) {
    this.stage2Activated = stage2Activated;
  }

  public MatchScoreBreakdown2020Alliance stage3Activated(Boolean stage3Activated) {
    this.stage3Activated = stage3Activated;
    return this;
  }

   /**
   * Get stage3Activated
   * @return stage3Activated
  **/
  @Schema(description = "")
  public Boolean isStage3Activated() {
    return stage3Activated;
  }

  public void setStage3Activated(Boolean stage3Activated) {
    this.stage3Activated = stage3Activated;
  }

  public MatchScoreBreakdown2020Alliance stage3TargetColor(String stage3TargetColor) {
    this.stage3TargetColor = stage3TargetColor;
    return this;
  }

   /**
   * Get stage3TargetColor
   * @return stage3TargetColor
  **/
  @Schema(description = "")
  public String getStage3TargetColor() {
    return stage3TargetColor;
  }

  public void setStage3TargetColor(String stage3TargetColor) {
    this.stage3TargetColor = stage3TargetColor;
  }

  public MatchScoreBreakdown2020Alliance endgameRungIsLevel(String endgameRungIsLevel) {
    this.endgameRungIsLevel = endgameRungIsLevel;
    return this;
  }

   /**
   * Get endgameRungIsLevel
   * @return endgameRungIsLevel
  **/
  @Schema(description = "")
  public String getEndgameRungIsLevel() {
    return endgameRungIsLevel;
  }

  public void setEndgameRungIsLevel(String endgameRungIsLevel) {
    this.endgameRungIsLevel = endgameRungIsLevel;
  }

  public MatchScoreBreakdown2020Alliance autoInitLinePoints(Integer autoInitLinePoints) {
    this.autoInitLinePoints = autoInitLinePoints;
    return this;
  }

   /**
   * Get autoInitLinePoints
   * @return autoInitLinePoints
  **/
  @Schema(description = "")
  public Integer getAutoInitLinePoints() {
    return autoInitLinePoints;
  }

  public void setAutoInitLinePoints(Integer autoInitLinePoints) {
    this.autoInitLinePoints = autoInitLinePoints;
  }

  public MatchScoreBreakdown2020Alliance autoCellPoints(Integer autoCellPoints) {
    this.autoCellPoints = autoCellPoints;
    return this;
  }

   /**
   * Get autoCellPoints
   * @return autoCellPoints
  **/
  @Schema(description = "")
  public Integer getAutoCellPoints() {
    return autoCellPoints;
  }

  public void setAutoCellPoints(Integer autoCellPoints) {
    this.autoCellPoints = autoCellPoints;
  }

  public MatchScoreBreakdown2020Alliance autoPoints(Integer autoPoints) {
    this.autoPoints = autoPoints;
    return this;
  }

   /**
   * Get autoPoints
   * @return autoPoints
  **/
  @Schema(description = "")
  public Integer getAutoPoints() {
    return autoPoints;
  }

  public void setAutoPoints(Integer autoPoints) {
    this.autoPoints = autoPoints;
  }

  public MatchScoreBreakdown2020Alliance teleopCellPoints(Integer teleopCellPoints) {
    this.teleopCellPoints = teleopCellPoints;
    return this;
  }

   /**
   * Get teleopCellPoints
   * @return teleopCellPoints
  **/
  @Schema(description = "")
  public Integer getTeleopCellPoints() {
    return teleopCellPoints;
  }

  public void setTeleopCellPoints(Integer teleopCellPoints) {
    this.teleopCellPoints = teleopCellPoints;
  }

  public MatchScoreBreakdown2020Alliance controlPanelPoints(Integer controlPanelPoints) {
    this.controlPanelPoints = controlPanelPoints;
    return this;
  }

   /**
   * Get controlPanelPoints
   * @return controlPanelPoints
  **/
  @Schema(description = "")
  public Integer getControlPanelPoints() {
    return controlPanelPoints;
  }

  public void setControlPanelPoints(Integer controlPanelPoints) {
    this.controlPanelPoints = controlPanelPoints;
  }

  public MatchScoreBreakdown2020Alliance endgamePoints(Integer endgamePoints) {
    this.endgamePoints = endgamePoints;
    return this;
  }

   /**
   * Get endgamePoints
   * @return endgamePoints
  **/
  @Schema(description = "")
  public Integer getEndgamePoints() {
    return endgamePoints;
  }

  public void setEndgamePoints(Integer endgamePoints) {
    this.endgamePoints = endgamePoints;
  }

  public MatchScoreBreakdown2020Alliance teleopPoints(Integer teleopPoints) {
    this.teleopPoints = teleopPoints;
    return this;
  }

   /**
   * Get teleopPoints
   * @return teleopPoints
  **/
  @Schema(description = "")
  public Integer getTeleopPoints() {
    return teleopPoints;
  }

  public void setTeleopPoints(Integer teleopPoints) {
    this.teleopPoints = teleopPoints;
  }

  public MatchScoreBreakdown2020Alliance shieldOperationalRankingPoint(Boolean shieldOperationalRankingPoint) {
    this.shieldOperationalRankingPoint = shieldOperationalRankingPoint;
    return this;
  }

   /**
   * Get shieldOperationalRankingPoint
   * @return shieldOperationalRankingPoint
  **/
  @Schema(description = "")
  public Boolean isShieldOperationalRankingPoint() {
    return shieldOperationalRankingPoint;
  }

  public void setShieldOperationalRankingPoint(Boolean shieldOperationalRankingPoint) {
    this.shieldOperationalRankingPoint = shieldOperationalRankingPoint;
  }

  public MatchScoreBreakdown2020Alliance shieldEnergizedRankingPoint(Boolean shieldEnergizedRankingPoint) {
    this.shieldEnergizedRankingPoint = shieldEnergizedRankingPoint;
    return this;
  }

   /**
   * Get shieldEnergizedRankingPoint
   * @return shieldEnergizedRankingPoint
  **/
  @Schema(description = "")
  public Boolean isShieldEnergizedRankingPoint() {
    return shieldEnergizedRankingPoint;
  }

  public void setShieldEnergizedRankingPoint(Boolean shieldEnergizedRankingPoint) {
    this.shieldEnergizedRankingPoint = shieldEnergizedRankingPoint;
  }

  public MatchScoreBreakdown2020Alliance tbaShieldEnergizedRankingPointFromFoul(Boolean tbaShieldEnergizedRankingPointFromFoul) {
    this.tbaShieldEnergizedRankingPointFromFoul = tbaShieldEnergizedRankingPointFromFoul;
    return this;
  }

   /**
   * Unofficial TBA-computed value that indicates whether the shieldEnergizedRankingPoint was earned normally or awarded due to a foul.
   * @return tbaShieldEnergizedRankingPointFromFoul
  **/
  @Schema(description = "Unofficial TBA-computed value that indicates whether the shieldEnergizedRankingPoint was earned normally or awarded due to a foul.")
  public Boolean isTbaShieldEnergizedRankingPointFromFoul() {
    return tbaShieldEnergizedRankingPointFromFoul;
  }

  public void setTbaShieldEnergizedRankingPointFromFoul(Boolean tbaShieldEnergizedRankingPointFromFoul) {
    this.tbaShieldEnergizedRankingPointFromFoul = tbaShieldEnergizedRankingPointFromFoul;
  }

  public MatchScoreBreakdown2020Alliance tbaNumRobotsHanging(Integer tbaNumRobotsHanging) {
    this.tbaNumRobotsHanging = tbaNumRobotsHanging;
    return this;
  }

   /**
   * Unofficial TBA-computed value that counts the number of robots who were hanging at the end of the match.
   * @return tbaNumRobotsHanging
  **/
  @Schema(description = "Unofficial TBA-computed value that counts the number of robots who were hanging at the end of the match.")
  public Integer getTbaNumRobotsHanging() {
    return tbaNumRobotsHanging;
  }

  public void setTbaNumRobotsHanging(Integer tbaNumRobotsHanging) {
    this.tbaNumRobotsHanging = tbaNumRobotsHanging;
  }

  public MatchScoreBreakdown2020Alliance foulCount(Integer foulCount) {
    this.foulCount = foulCount;
    return this;
  }

   /**
   * Get foulCount
   * @return foulCount
  **/
  @Schema(description = "")
  public Integer getFoulCount() {
    return foulCount;
  }

  public void setFoulCount(Integer foulCount) {
    this.foulCount = foulCount;
  }

  public MatchScoreBreakdown2020Alliance techFoulCount(Integer techFoulCount) {
    this.techFoulCount = techFoulCount;
    return this;
  }

   /**
   * Get techFoulCount
   * @return techFoulCount
  **/
  @Schema(description = "")
  public Integer getTechFoulCount() {
    return techFoulCount;
  }

  public void setTechFoulCount(Integer techFoulCount) {
    this.techFoulCount = techFoulCount;
  }

  public MatchScoreBreakdown2020Alliance adjustPoints(Integer adjustPoints) {
    this.adjustPoints = adjustPoints;
    return this;
  }

   /**
   * Get adjustPoints
   * @return adjustPoints
  **/
  @Schema(description = "")
  public Integer getAdjustPoints() {
    return adjustPoints;
  }

  public void setAdjustPoints(Integer adjustPoints) {
    this.adjustPoints = adjustPoints;
  }

  public MatchScoreBreakdown2020Alliance foulPoints(Integer foulPoints) {
    this.foulPoints = foulPoints;
    return this;
  }

   /**
   * Get foulPoints
   * @return foulPoints
  **/
  @Schema(description = "")
  public Integer getFoulPoints() {
    return foulPoints;
  }

  public void setFoulPoints(Integer foulPoints) {
    this.foulPoints = foulPoints;
  }

  public MatchScoreBreakdown2020Alliance rp(Integer rp) {
    this.rp = rp;
    return this;
  }

   /**
   * Get rp
   * @return rp
  **/
  @Schema(description = "")
  public Integer getRp() {
    return rp;
  }

  public void setRp(Integer rp) {
    this.rp = rp;
  }

  public MatchScoreBreakdown2020Alliance totalPoints(Integer totalPoints) {
    this.totalPoints = totalPoints;
    return this;
  }

   /**
   * Get totalPoints
   * @return totalPoints
  **/
  @Schema(description = "")
  public Integer getTotalPoints() {
    return totalPoints;
  }

  public void setTotalPoints(Integer totalPoints) {
    this.totalPoints = totalPoints;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchScoreBreakdown2020Alliance matchScoreBreakdown2020Alliance = (MatchScoreBreakdown2020Alliance) o;
    return Objects.equals(this.initLineRobot1, matchScoreBreakdown2020Alliance.initLineRobot1) &&
        Objects.equals(this.endgameRobot1, matchScoreBreakdown2020Alliance.endgameRobot1) &&
        Objects.equals(this.initLineRobot2, matchScoreBreakdown2020Alliance.initLineRobot2) &&
        Objects.equals(this.endgameRobot2, matchScoreBreakdown2020Alliance.endgameRobot2) &&
        Objects.equals(this.initLineRobot3, matchScoreBreakdown2020Alliance.initLineRobot3) &&
        Objects.equals(this.endgameRobot3, matchScoreBreakdown2020Alliance.endgameRobot3) &&
        Objects.equals(this.autoCellsBottom, matchScoreBreakdown2020Alliance.autoCellsBottom) &&
        Objects.equals(this.autoCellsOuter, matchScoreBreakdown2020Alliance.autoCellsOuter) &&
        Objects.equals(this.autoCellsInner, matchScoreBreakdown2020Alliance.autoCellsInner) &&
        Objects.equals(this.teleopCellsBottom, matchScoreBreakdown2020Alliance.teleopCellsBottom) &&
        Objects.equals(this.teleopCellsOuter, matchScoreBreakdown2020Alliance.teleopCellsOuter) &&
        Objects.equals(this.teleopCellsInner, matchScoreBreakdown2020Alliance.teleopCellsInner) &&
        Objects.equals(this.stage1Activated, matchScoreBreakdown2020Alliance.stage1Activated) &&
        Objects.equals(this.stage2Activated, matchScoreBreakdown2020Alliance.stage2Activated) &&
        Objects.equals(this.stage3Activated, matchScoreBreakdown2020Alliance.stage3Activated) &&
        Objects.equals(this.stage3TargetColor, matchScoreBreakdown2020Alliance.stage3TargetColor) &&
        Objects.equals(this.endgameRungIsLevel, matchScoreBreakdown2020Alliance.endgameRungIsLevel) &&
        Objects.equals(this.autoInitLinePoints, matchScoreBreakdown2020Alliance.autoInitLinePoints) &&
        Objects.equals(this.autoCellPoints, matchScoreBreakdown2020Alliance.autoCellPoints) &&
        Objects.equals(this.autoPoints, matchScoreBreakdown2020Alliance.autoPoints) &&
        Objects.equals(this.teleopCellPoints, matchScoreBreakdown2020Alliance.teleopCellPoints) &&
        Objects.equals(this.controlPanelPoints, matchScoreBreakdown2020Alliance.controlPanelPoints) &&
        Objects.equals(this.endgamePoints, matchScoreBreakdown2020Alliance.endgamePoints) &&
        Objects.equals(this.teleopPoints, matchScoreBreakdown2020Alliance.teleopPoints) &&
        Objects.equals(this.shieldOperationalRankingPoint, matchScoreBreakdown2020Alliance.shieldOperationalRankingPoint) &&
        Objects.equals(this.shieldEnergizedRankingPoint, matchScoreBreakdown2020Alliance.shieldEnergizedRankingPoint) &&
        Objects.equals(this.tbaShieldEnergizedRankingPointFromFoul, matchScoreBreakdown2020Alliance.tbaShieldEnergizedRankingPointFromFoul) &&
        Objects.equals(this.tbaNumRobotsHanging, matchScoreBreakdown2020Alliance.tbaNumRobotsHanging) &&
        Objects.equals(this.foulCount, matchScoreBreakdown2020Alliance.foulCount) &&
        Objects.equals(this.techFoulCount, matchScoreBreakdown2020Alliance.techFoulCount) &&
        Objects.equals(this.adjustPoints, matchScoreBreakdown2020Alliance.adjustPoints) &&
        Objects.equals(this.foulPoints, matchScoreBreakdown2020Alliance.foulPoints) &&
        Objects.equals(this.rp, matchScoreBreakdown2020Alliance.rp) &&
        Objects.equals(this.totalPoints, matchScoreBreakdown2020Alliance.totalPoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(initLineRobot1, endgameRobot1, initLineRobot2, endgameRobot2, initLineRobot3, endgameRobot3, autoCellsBottom, autoCellsOuter, autoCellsInner, teleopCellsBottom, teleopCellsOuter, teleopCellsInner, stage1Activated, stage2Activated, stage3Activated, stage3TargetColor, endgameRungIsLevel, autoInitLinePoints, autoCellPoints, autoPoints, teleopCellPoints, controlPanelPoints, endgamePoints, teleopPoints, shieldOperationalRankingPoint, shieldEnergizedRankingPoint, tbaShieldEnergizedRankingPointFromFoul, tbaNumRobotsHanging, foulCount, techFoulCount, adjustPoints, foulPoints, rp, totalPoints);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchScoreBreakdown2020Alliance {\n");
    
    sb.append("    initLineRobot1: ").append(toIndentedString(initLineRobot1)).append("\n");
    sb.append("    endgameRobot1: ").append(toIndentedString(endgameRobot1)).append("\n");
    sb.append("    initLineRobot2: ").append(toIndentedString(initLineRobot2)).append("\n");
    sb.append("    endgameRobot2: ").append(toIndentedString(endgameRobot2)).append("\n");
    sb.append("    initLineRobot3: ").append(toIndentedString(initLineRobot3)).append("\n");
    sb.append("    endgameRobot3: ").append(toIndentedString(endgameRobot3)).append("\n");
    sb.append("    autoCellsBottom: ").append(toIndentedString(autoCellsBottom)).append("\n");
    sb.append("    autoCellsOuter: ").append(toIndentedString(autoCellsOuter)).append("\n");
    sb.append("    autoCellsInner: ").append(toIndentedString(autoCellsInner)).append("\n");
    sb.append("    teleopCellsBottom: ").append(toIndentedString(teleopCellsBottom)).append("\n");
    sb.append("    teleopCellsOuter: ").append(toIndentedString(teleopCellsOuter)).append("\n");
    sb.append("    teleopCellsInner: ").append(toIndentedString(teleopCellsInner)).append("\n");
    sb.append("    stage1Activated: ").append(toIndentedString(stage1Activated)).append("\n");
    sb.append("    stage2Activated: ").append(toIndentedString(stage2Activated)).append("\n");
    sb.append("    stage3Activated: ").append(toIndentedString(stage3Activated)).append("\n");
    sb.append("    stage3TargetColor: ").append(toIndentedString(stage3TargetColor)).append("\n");
    sb.append("    endgameRungIsLevel: ").append(toIndentedString(endgameRungIsLevel)).append("\n");
    sb.append("    autoInitLinePoints: ").append(toIndentedString(autoInitLinePoints)).append("\n");
    sb.append("    autoCellPoints: ").append(toIndentedString(autoCellPoints)).append("\n");
    sb.append("    autoPoints: ").append(toIndentedString(autoPoints)).append("\n");
    sb.append("    teleopCellPoints: ").append(toIndentedString(teleopCellPoints)).append("\n");
    sb.append("    controlPanelPoints: ").append(toIndentedString(controlPanelPoints)).append("\n");
    sb.append("    endgamePoints: ").append(toIndentedString(endgamePoints)).append("\n");
    sb.append("    teleopPoints: ").append(toIndentedString(teleopPoints)).append("\n");
    sb.append("    shieldOperationalRankingPoint: ").append(toIndentedString(shieldOperationalRankingPoint)).append("\n");
    sb.append("    shieldEnergizedRankingPoint: ").append(toIndentedString(shieldEnergizedRankingPoint)).append("\n");
    sb.append("    tbaShieldEnergizedRankingPointFromFoul: ").append(toIndentedString(tbaShieldEnergizedRankingPointFromFoul)).append("\n");
    sb.append("    tbaNumRobotsHanging: ").append(toIndentedString(tbaNumRobotsHanging)).append("\n");
    sb.append("    foulCount: ").append(toIndentedString(foulCount)).append("\n");
    sb.append("    techFoulCount: ").append(toIndentedString(techFoulCount)).append("\n");
    sb.append("    adjustPoints: ").append(toIndentedString(adjustPoints)).append("\n");
    sb.append("    foulPoints: ").append(toIndentedString(foulPoints)).append("\n");
    sb.append("    rp: ").append(toIndentedString(rp)).append("\n");
    sb.append("    totalPoints: ").append(toIndentedString(totalPoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
