/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.TeamEventStatusAlliance;
import io.swagger.client.model.TeamEventStatusPlayoff;
import io.swagger.client.model.TeamEventStatusRank;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * TeamEventStatus
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-26T16:01:43.676Z[GMT]")
public class TeamEventStatus {
  @SerializedName("qual")
  private TeamEventStatusRank qual = null;

  @SerializedName("alliance")
  private TeamEventStatusAlliance alliance = null;

  @SerializedName("playoff")
  private TeamEventStatusPlayoff playoff = null;

  @SerializedName("alliance_status_str")
  private String allianceStatusStr = null;

  @SerializedName("playoff_status_str")
  private String playoffStatusStr = null;

  @SerializedName("overall_status_str")
  private String overallStatusStr = null;

  @SerializedName("next_match_key")
  private String nextMatchKey = null;

  @SerializedName("last_match_key")
  private String lastMatchKey = null;

  public TeamEventStatus qual(TeamEventStatusRank qual) {
    this.qual = qual;
    return this;
  }

   /**
   * Get qual
   * @return qual
  **/
  @Schema(description = "")
  public TeamEventStatusRank getQual() {
    return qual;
  }

  public void setQual(TeamEventStatusRank qual) {
    this.qual = qual;
  }

  public TeamEventStatus alliance(TeamEventStatusAlliance alliance) {
    this.alliance = alliance;
    return this;
  }

   /**
   * Get alliance
   * @return alliance
  **/
  @Schema(description = "")
  public TeamEventStatusAlliance getAlliance() {
    return alliance;
  }

  public void setAlliance(TeamEventStatusAlliance alliance) {
    this.alliance = alliance;
  }

  public TeamEventStatus playoff(TeamEventStatusPlayoff playoff) {
    this.playoff = playoff;
    return this;
  }

   /**
   * Get playoff
   * @return playoff
  **/
  @Schema(description = "")
  public TeamEventStatusPlayoff getPlayoff() {
    return playoff;
  }

  public void setPlayoff(TeamEventStatusPlayoff playoff) {
    this.playoff = playoff;
  }

  public TeamEventStatus allianceStatusStr(String allianceStatusStr) {
    this.allianceStatusStr = allianceStatusStr;
    return this;
  }

   /**
   * An HTML formatted string suitable for display to the user containing the team&#x27;s alliance pick status.
   * @return allianceStatusStr
  **/
  @Schema(description = "An HTML formatted string suitable for display to the user containing the team's alliance pick status.")
  public String getAllianceStatusStr() {
    return allianceStatusStr;
  }

  public void setAllianceStatusStr(String allianceStatusStr) {
    this.allianceStatusStr = allianceStatusStr;
  }

  public TeamEventStatus playoffStatusStr(String playoffStatusStr) {
    this.playoffStatusStr = playoffStatusStr;
    return this;
  }

   /**
   * An HTML formatter string suitable for display to the user containing the team&#x27;s playoff status.
   * @return playoffStatusStr
  **/
  @Schema(description = "An HTML formatter string suitable for display to the user containing the team's playoff status.")
  public String getPlayoffStatusStr() {
    return playoffStatusStr;
  }

  public void setPlayoffStatusStr(String playoffStatusStr) {
    this.playoffStatusStr = playoffStatusStr;
  }

  public TeamEventStatus overallStatusStr(String overallStatusStr) {
    this.overallStatusStr = overallStatusStr;
    return this;
  }

   /**
   * An HTML formatted string suitable for display to the user containing the team&#x27;s overall status summary of the event.
   * @return overallStatusStr
  **/
  @Schema(description = "An HTML formatted string suitable for display to the user containing the team's overall status summary of the event.")
  public String getOverallStatusStr() {
    return overallStatusStr;
  }

  public void setOverallStatusStr(String overallStatusStr) {
    this.overallStatusStr = overallStatusStr;
  }

  public TeamEventStatus nextMatchKey(String nextMatchKey) {
    this.nextMatchKey = nextMatchKey;
    return this;
  }

   /**
   * TBA match key for the next match the team is scheduled to play in at this event, or null.
   * @return nextMatchKey
  **/
  @Schema(description = "TBA match key for the next match the team is scheduled to play in at this event, or null.")
  public String getNextMatchKey() {
    return nextMatchKey;
  }

  public void setNextMatchKey(String nextMatchKey) {
    this.nextMatchKey = nextMatchKey;
  }

  public TeamEventStatus lastMatchKey(String lastMatchKey) {
    this.lastMatchKey = lastMatchKey;
    return this;
  }

   /**
   * TBA match key for the last match the team played in at this event, or null.
   * @return lastMatchKey
  **/
  @Schema(description = "TBA match key for the last match the team played in at this event, or null.")
  public String getLastMatchKey() {
    return lastMatchKey;
  }

  public void setLastMatchKey(String lastMatchKey) {
    this.lastMatchKey = lastMatchKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamEventStatus teamEventStatus = (TeamEventStatus) o;
    return Objects.equals(this.qual, teamEventStatus.qual) &&
        Objects.equals(this.alliance, teamEventStatus.alliance) &&
        Objects.equals(this.playoff, teamEventStatus.playoff) &&
        Objects.equals(this.allianceStatusStr, teamEventStatus.allianceStatusStr) &&
        Objects.equals(this.playoffStatusStr, teamEventStatus.playoffStatusStr) &&
        Objects.equals(this.overallStatusStr, teamEventStatus.overallStatusStr) &&
        Objects.equals(this.nextMatchKey, teamEventStatus.nextMatchKey) &&
        Objects.equals(this.lastMatchKey, teamEventStatus.lastMatchKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(qual, alliance, playoff, allianceStatusStr, playoffStatusStr, overallStatusStr, nextMatchKey, lastMatchKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamEventStatus {\n");
    
    sb.append("    qual: ").append(toIndentedString(qual)).append("\n");
    sb.append("    alliance: ").append(toIndentedString(alliance)).append("\n");
    sb.append("    playoff: ").append(toIndentedString(playoff)).append("\n");
    sb.append("    allianceStatusStr: ").append(toIndentedString(allianceStatusStr)).append("\n");
    sb.append("    playoffStatusStr: ").append(toIndentedString(playoffStatusStr)).append("\n");
    sb.append("    overallStatusStr: ").append(toIndentedString(overallStatusStr)).append("\n");
    sb.append("    nextMatchKey: ").append(toIndentedString(nextMatchKey)).append("\n");
    sb.append("    lastMatchKey: ").append(toIndentedString(lastMatchKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
