/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.DistrictList;
import io.swagger.client.model.DistrictRanking;
import io.swagger.client.model.Event;
import io.swagger.client.model.EventDistrictPoints;
import io.swagger.client.model.EventSimple;
import io.swagger.client.model.Team;
import io.swagger.client.model.TeamSimple;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DistrictApi
 */
@Ignore
public class DistrictApiTest {

    private final DistrictApi api = new DistrictApi();

    /**
     * 
     *
     * Gets a list of events in the given district.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDistrictEventsTest() throws Exception {
        String districtKey = null;
        String ifModifiedSince = null;
        List<Event> response = api.getDistrictEvents(districtKey, ifModifiedSince);

        // TODO: test validations
    }
    /**
     * 
     *
     * Gets a list of event keys for events in the given district.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDistrictEventsKeysTest() throws Exception {
        String districtKey = null;
        String ifModifiedSince = null;
        List<String> response = api.getDistrictEventsKeys(districtKey, ifModifiedSince);

        // TODO: test validations
    }
    /**
     * 
     *
     * Gets a short-form list of events in the given district.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDistrictEventsSimpleTest() throws Exception {
        String districtKey = null;
        String ifModifiedSince = null;
        List<EventSimple> response = api.getDistrictEventsSimple(districtKey, ifModifiedSince);

        // TODO: test validations
    }
    /**
     * 
     *
     * Gets a list of team district rankings for the given district.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDistrictRankingsTest() throws Exception {
        String districtKey = null;
        String ifModifiedSince = null;
        List<DistrictRanking> response = api.getDistrictRankings(districtKey, ifModifiedSince);

        // TODO: test validations
    }
    /**
     * 
     *
     * Gets a list of &#x60;Team&#x60; objects that competed in events in the given district.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDistrictTeamsTest() throws Exception {
        String districtKey = null;
        String ifModifiedSince = null;
        List<Team> response = api.getDistrictTeams(districtKey, ifModifiedSince);

        // TODO: test validations
    }
    /**
     * 
     *
     * Gets a list of &#x60;Team&#x60; objects that competed in events in the given district.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDistrictTeamsKeysTest() throws Exception {
        String districtKey = null;
        String ifModifiedSince = null;
        List<String> response = api.getDistrictTeamsKeys(districtKey, ifModifiedSince);

        // TODO: test validations
    }
    /**
     * 
     *
     * Gets a short-form list of &#x60;Team&#x60; objects that competed in events in the given district.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDistrictTeamsSimpleTest() throws Exception {
        String districtKey = null;
        String ifModifiedSince = null;
        List<TeamSimple> response = api.getDistrictTeamsSimple(districtKey, ifModifiedSince);

        // TODO: test validations
    }
    /**
     * 
     *
     * Gets a list of districts and their corresponding district key, for the given year.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDistrictsByYearTest() throws Exception {
        Integer year = null;
        String ifModifiedSince = null;
        List<DistrictList> response = api.getDistrictsByYear(year, ifModifiedSince);

        // TODO: test validations
    }
    /**
     * 
     *
     * Gets a list of team rankings for the Event.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getEventDistrictPointsTest() throws Exception {
        String eventKey = null;
        String ifModifiedSince = null;
        EventDistrictPoints response = api.getEventDistrictPoints(eventKey, ifModifiedSince);

        // TODO: test validations
    }
    /**
     * 
     *
     * Gets an array of districts representing each year the team was in a district. Will return an empty array if the team was never in a district.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTeamDistrictsTest() throws Exception {
        String teamKey = null;
        String ifModifiedSince = null;
        List<DistrictList> response = api.getTeamDistricts(teamKey, ifModifiedSince);

        // TODO: test validations
    }
}
