/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.APIStatus;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for TbaApi
 */
@Ignore
public class TbaApiTest {

    private final TbaApi api = new TbaApi();

    /**
     * 
     *
     * Returns API status, and TBA status information.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getStatusTest() throws Exception {
        String ifModifiedSince = null;
        APIStatus response = api.getStatus(ifModifiedSince);

        // TODO: test validations
    }
}
